<a href="https://colab.research.google.com/github/CarlosNoriegaPolo/fMetRecogninPrediction/blob/colab_development/fMet_Recognin_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **fMet Recognin Prediction Project**

### **Coding Rules for This Project**

*   **Write Clear Code**: Use meaningful variable and function names.

*   **Comment Your Code**: Briefly explain your code and reasoning.

*   **Keep It Organized**: Use different sections to develop and test individual portions of the code.

*   **Incorporate Checks**: Frequently check the output of code blocks by printing statements and execution times

# Part 0. Load libraries

Load all the neccesary libraries here.

In [28]:
import requests # for API requests
import re # regular expressions
import time # to control running times
from tqdm import tqdm # progress bars
import pandas as pd # to make DataFrame

# Part 1. Retrieve Protein Models - Data Mining

## Get all reviewed human proteins from UniProt API

In [ ]:
# Set parameters
batch_size = 500 # it will retrieve entries in groups of 500 (can change)
base_url = "https://rest.uniprot.org/uniprotkb/search"
re_next_link = re.compile(r'<(.+)>; rel="next"')

# Set up session with retry strategy
session = requests.Session()
retry_strategy = requests.adapters.Retry(
    total=5, backoff_factor=0.25, status_forcelist=[500, 502, 503, 504] # these are the codes for failed attempts
)
session.mount("https://", requests.adapters.HTTPAdapter(max_retries=retry_strategy))

# Construct query parameters (explicitly requesting only the necessary fields)
params = {
    'query': '(reviewed:true) AND (organism_id:9606)',  # 9606 is the taxonomy ID for humans
    'format': 'tsv',
    'fields': 'accession,protein_name',  # Request only UniProt ID and protein name
    'size': batch_size
}

# Construct initial URL
url = f"{base_url}?{'&'.join(f'{k}={v}' for k, v in params.items())}"

# Initialize dictionary to store protein data
uniprot_IDs = []
protein_IDs = {}
progress = 0

# Start timer for total time
start_time = time.time()

# Fetch and process batches
while url:
    try:
        # Send request and get response
        response = session.get(url)
        response.raise_for_status()

        # Parse the response
        lines = response.text.splitlines()

        # Process the data (skip header)
        for line in lines[1:]:  # Skip the header
            fields = line.split("\t")
            if len(fields) >= 2:  # Ensure there are at least two columns
                uniprot_id, protein_name = fields[:2]  # Take only the first two values

                uniprot_IDs.append(uniprot_id)
                protein_IDs[protein_name] = uniprot_id

        # Update progress
        progress += len(lines[1:])
        total = response.headers.get("x-total-results", "unknown")
        print(f"Progress: {progress:,} / {int(total):,} entries",
              f"({progress/int(total)*100:.1f}%)")

        # Extract the next page URL from headers (pagination)
        next_link = response.headers.get("Link")
        if next_link:
            match = re.search(r'<(.+)>; rel="next"', next_link)
            url = match.group(1) if match else None
        else:
            url = None

    except requests.exceptions.RequestException as e:
        print(f"Error fetching batch: {e}")
        break

# Calculate and print total time
duration = time.time() - start_time
print(f"\nDownload completed in {duration:.1f} seconds")
print(f"Total proteins: {len(protein_IDs)}")

Progress: 500 / 20,417 entries (2.4%)
Progress: 1,000 / 20,417 entries (4.9%)
Progress: 1,500 / 20,417 entries (7.3%)
Progress: 2,000 / 20,417 entries (9.8%)
Progress: 2,500 / 20,417 entries (12.2%)
Progress: 3,000 / 20,417 entries (14.7%)
Progress: 3,500 / 20,417 entries (17.1%)
Progress: 4,000 / 20,417 entries (19.6%)
Progress: 4,500 / 20,417 entries (22.0%)
Progress: 5,000 / 20,417 entries (24.5%)
Progress: 5,500 / 20,417 entries (26.9%)
Progress: 6,000 / 20,417 entries (29.4%)
Progress: 6,500 / 20,417 entries (31.8%)
Progress: 7,000 / 20,417 entries (34.3%)
Progress: 7,500 / 20,417 entries (36.7%)
Progress: 8,000 / 20,417 entries (39.2%)
Progress: 8,500 / 20,417 entries (41.6%)
Progress: 9,000 / 20,417 entries (44.1%)
Progress: 9,500 / 20,417 entries (46.5%)
Progress: 10,000 / 20,417 entries (49.0%)
Progress: 10,500 / 20,417 entries (51.4%)
Progress: 11,000 / 20,417 entries (53.9%)
Progress: 11,500 / 20,417 entries (56.3%)
Progress: 12,000 / 20,417 entries (58.8%)
Progress: 12,500 / 20,417 entries (61.2%)
Progress: 13,000 / 20,417 entries (63.7%)
Progress: 13,500 / 20,417 entries (66.1%)
Progress: 14,000 / 20,417 entries (68.6%)
Progress: 14,500 / 20,417 entries (71.0%)
Progress: 15,000 / 20,417 entries (73.5%)
Progress: 15,500 / 20,417 entries (75.9%)
Progress: 16,000 / 20,417 entries (78.4%)
Progress: 16,500 / 20,417 entries (80.8%)
Progress: 17,000 / 20,417 entries (83.3%)
Progress: 17,500 / 20,417 entries (85.7%)
Progress: 18,000 / 20,417 entries (88.2%)
Progress: 18,500 / 20,417 entries (90.6%)
Progress: 19,000 / 20,417 entries (93.1%)
Progress: 19,500 / 20,417 entries (95.5%)
Progress: 20,000 / 20,417 entries (98.0%)
Progress: 20,417 / 20,417 entries (100.0%)

Download completed in 107.1 seconds
Total proteins: 20417

In [ ]:
# Check the first 10 items of the protein_IDs dictionary
for i, (protein_name, uniprot_id) in enumerate(protein_IDs.items()):
    if i < 10:
        print(f"Protein ID: {uniprot_id} Protein Name: {protein_name}")

Protein ID: A0A0C5B5G6 Protein Name: Mitochondrial-derived peptide MOTS-c (Mitochondrial open reading frame of the 12S rRNA-c)
Protein ID: A0A1B0GTW7 Protein Name: Ciliated left-right organizer metallopeptidase (EC 3.4.24.-) (Leishmanolysin-like peptidase 2)
Protein ID: A0JNW5 Protein Name: Bridge-like lipid transfer protein family member 3B (Syntaxin-6 Habc-interacting protein of 164 kDa) (UHRF1-binding protein 1-like)
Protein ID: A0JP26 Protein Name: POTE ankyrin domain family member B3
Protein ID: A0PK11 Protein Name: Clarin-2
Protein ID: A1A4S6 Protein Name: Rho GTPase-activating protein 10 (GTPase regulator associated with focal adhesion kinase 2) (GRAF2) (Graf-related protein 2) (Rho-type GTPase-activating protein 10)
Protein ID: A1A519 Protein Name: Protein FAM170A (Zinc finger domain-containing protein) (Zinc finger protein ZNFD)
Protein ID: A1L190 Protein Name: Synaptonemal complex central element protein 3 (Testis highly expressed gene 2 protein) (THEG-2)
Protein ID: A1L3X0 Protein Name: Very long chain fatty acid elongase 7 (EC 2.3.1.199) (3-keto acyl-CoA synthase ELOVL7) (ELOVL fatty acid elongase 7) (ELOVL FA elongase 7) (Elongation of very long chain fatty acids protein 7) (Very long chain 3-ketoacyl-CoA synthase 7) (Very long chain 3-oxoacyl-CoA synthase 7)
Protein ID: A1X283 Protein Name: SH3 and PX domain-containing protein 2B (Adapter protein HOFI) (Factor for adipocyte differentiation 49) (Tyrosine kinase substrate with four SH3 domains)

## Get data for **features** and explore it

Start by using the UniProt IDs stored in the protein_IDs dictionary. Using the UniProt API, extract all information regarding the features for each protein and append this information into a dataframe. Then analyse this further to completely understand our data i.e. what are all of the possible labels, what are the average positions/lengths of each feature, etc.

In [81]:
# Use the previously generated protein_IDs dictionary to create a list of all UniProt IDs to fetch
uniprot_ids_to_fetch = list(protein_IDs.values())

# Set parameters
batch_size = 200  # Slightly smaller batch size when we want to search for more information
base_url = "https://rest.uniprot.org/uniprotkb/search"

# Set up session with retry strategy
session = requests.Session()
retry_strategy = requests.adapters.Retry(
    total=5, backoff_factor=0.25, status_forcelist=[500, 502, 503, 504]
)
session.mount("https://", requests.adapters.HTTPAdapter(max_retries=retry_strategy))

# Prepare an empty DataFrame to store results
features_df = pd.DataFrame(columns=['accession', 'protein_name', 'total_length',
                                   'signal_peptide', 'signal_start', 'signal_end',
                                   'transit_peptide', 'transit_start', 'transit_end'])

# Process in batches to avoid overwhelming the API
total_ids = len(uniprot_ids_to_fetch)
processed = 0
batch_num = 0

# Start timer
start_time = time.time()

# Process in batches
for i in range(0, total_ids, batch_size):
    batch_num += 1
    batch_ids = uniprot_ids_to_fetch[i:i+batch_size]

    # Construct the query with OR conditions for each ID
    id_query = " OR ".join([f"accession:{acc}" for acc in batch_ids])

    # Construct query parameters
    params = {
        'query': f'({id_query})',
        'format': 'tsv',
        'fields': 'accession,protein_name,ft_signal,ft_transit,length',
        'size': batch_size
    }

    # Construct initial URL
    url = f"{base_url}?{'&'.join(f'{k}={v}' for k, v in params.items())}"

    try:
        # Send request and get response
        response = session.get(url)
        response.raise_for_status()

        # Parse the response
        lines = response.text.splitlines()

        # Process the data (skip header)
        batch_data = []
        for line in lines[1:]:  # Skip the header
            fields = line.split("\t")

            # Ensure we have at least 5 columns (some may be empty)
            if len(fields) < 5:
                fields.extend([''] * (5 - len(fields)))

            # Extract basic information
            accession = fields[0]
            protein_name = fields[1]
            ft_signal = fields[2] if fields[2] else 'None'
            ft_transit = fields[3] if fields[3] else 'None'
            total_length = fields[4]

            # Process signal peptide information
            signal_peptide = 0
            signal_start = None
            signal_end = None

            if ft_signal != 'None':
                signal_peptide = 1
                signal_match = re.search(r'SIGNAL (\d+)\.\.(\d+)', ft_signal)
                if signal_match:
                    signal_start = int(signal_match.group(1))
                    signal_end = int(signal_match.group(2))

            # Process transit peptide information
            transit_peptide = 0
            transit_start = None
            transit_end = None

            if ft_transit != 'None':
                transit_peptide = 1
                transit_match = re.search(r'TRANSIT (\d+)\.\.(\d+)', ft_transit)
                if transit_match:
                    transit_start = int(transit_match.group(1))
                    transit_end = int(transit_match.group(2))

            # Add processed data to the batch
            batch_data.append([
                accession, protein_name, total_length,
                signal_peptide, signal_start, signal_end,
                transit_peptide, transit_start, transit_end
            ])

        # Add to DataFrame
        temp_df = pd.DataFrame(batch_data, columns=[
            'accession', 'protein_name', 'total_length',
            'signal_peptide', 'signal_start', 'signal_end',
            'transit_peptide', 'transit_start', 'transit_end'
        ])
        features_df = pd.concat([features_df, temp_df], ignore_index=True)

        # Update progress
        processed += len(batch_ids)
        print(f"Progress: {processed:,} / {total_ids:,} proteins ({processed/total_ids*100:.1f}%)")

        # Sleep briefly to avoid overwhelming the API
        time.sleep(0.5)

    except requests.exceptions.RequestException as e:
        print(f"Error fetching batch {batch_num}: {e}")
        # Continue with next batch instead of breaking
        continue

# Calculate and print total time
duration = time.time() - start_time
print(f"\nData extraction completed in {duration:.1f} seconds")
print(f"Total proteins processed: {processed:,} out of {total_ids:,}")

# Convert length to integer where possible
features_df['total_length'] = pd.to_numeric(features_df['total_length'], errors='coerce')

<ipython-input-81-2e0f62e63c0f>:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  features_df = pd.concat([features_df, temp_df], ignore_index=True)

Progress: 200 / 20,417 proteins (1.0%)
Progress: 400 / 20,417 proteins (2.0%)
Progress: 600 / 20,417 proteins (2.9%)
Progress: 800 / 20,417 proteins (3.9%)
Progress: 1,000 / 20,417 proteins (4.9%)
Progress: 1,200 / 20,417 proteins (5.9%)
Progress: 1,400 / 20,417 proteins (6.9%)
Progress: 1,600 / 20,417 proteins (7.8%)
Progress: 1,800 / 20,417 proteins (8.8%)
Progress: 2,000 / 20,417 proteins (9.8%)
Progress: 2,200 / 20,417 proteins (10.8%)
Progress: 2,400 / 20,417 proteins (11.8%)
Progress: 2,600 / 20,417 proteins (12.7%)
Progress: 2,800 / 20,417 proteins (13.7%)
Progress: 3,000 / 20,417 proteins (14.7%)
Progress: 3,200 / 20,417 proteins (15.7%)
Progress: 3,400 / 20,417 proteins (16.7%)
Progress: 3,600 / 20,417 proteins (17.6%)
Progress: 3,800 / 20,417 proteins (18.6%)
Progress: 4,000 / 20,417 proteins (19.6%)
Progress: 4,200 / 20,417 proteins (20.6%)
Progress: 4,400 / 20,417 proteins (21.6%)
Progress: 4,600 / 20,417 proteins (22.5%)
Progress: 4,800 / 20,417 proteins (23.5%)
Progress: 5,000 / 20,417 proteins (24.5%)
Progress: 5,200 / 20,417 proteins (25.5%)
Progress: 5,400 / 20,417 proteins (26.4%)
Progress: 5,600 / 20,417 proteins (27.4%)
Progress: 5,800 / 20,417 proteins (28.4%)
Progress: 6,000 / 20,417 proteins (29.4%)
Progress: 6,200 / 20,417 proteins (30.4%)
Progress: 6,400 / 20,417 proteins (31.3%)
Progress: 6,600 / 20,417 proteins (32.3%)
Progress: 6,800 / 20,417 proteins (33.3%)
Progress: 7,000 / 20,417 proteins (34.3%)
Progress: 7,200 / 20,417 proteins (35.3%)
Progress: 7,400 / 20,417 proteins (36.2%)
Progress: 7,600 / 20,417 proteins (37.2%)
Progress: 7,800 / 20,417 proteins (38.2%)
Progress: 8,000 / 20,417 proteins (39.2%)
Progress: 8,200 / 20,417 proteins (40.2%)
Progress: 8,400 / 20,417 proteins (41.1%)
Progress: 8,600 / 20,417 proteins (42.1%)
Progress: 8,800 / 20,417 proteins (43.1%)
Progress: 9,000 / 20,417 proteins (44.1%)
Progress: 9,200 / 20,417 proteins (45.1%)
Progress: 9,400 / 20,417 proteins (46.0%)
Progress: 9,600 / 20,417 proteins (47.0%)
Progress: 9,800 / 20,417 proteins (48.0%)
Progress: 10,000 / 20,417 proteins (49.0%)
Progress: 10,200 / 20,417 proteins (50.0%)
Progress: 10,400 / 20,417 proteins (50.9%)
Progress: 10,600 / 20,417 proteins (51.9%)
Progress: 10,800 / 20,417 proteins (52.9%)
Progress: 11,000 / 20,417 proteins (53.9%)
Progress: 11,200 / 20,417 proteins (54.9%)
Progress: 11,400 / 20,417 proteins (55.8%)
Progress: 11,600 / 20,417 proteins (56.8%)
Progress: 11,800 / 20,417 proteins (57.8%)
Progress: 12,000 / 20,417 proteins (58.8%)

KeyboardInterrupt:

In [49]:
# Check the dataframe
features_df.head(50)

,accession,protein_name,total_length,signal_peptide,signal_start,signal_end,transit_peptide,transit_start,transit_end
0,A0A0C5B5G6,Mitochondrial-derived peptide MOTS-c (Mitochon...,16,0,NaN,NaN,0,NaN,NaN
1,A0A1B0GTW7,Ciliated left-right organizer metallopeptidase...,788,1,1.0,20.0,0,NaN,NaN
2,A0JNW5,Bridge-like lipid transfer protein family memb...,1464,0,NaN,NaN,0,NaN,NaN
3,A0JP26,POTE ankyrin domain family member B3,581,0,NaN,NaN,0,NaN,NaN
4,A0PK11,Clarin-2,232,0,NaN,NaN,0,NaN,NaN
5,A1A4S6,Rho GTPase-activating protein 10 (GTPase regul...,786,0,NaN,NaN,0,NaN,NaN
6,A1L190,Synaptonemal complex central element protein 3...,88,0,NaN,NaN,0,NaN,NaN
7,A1L3X0,Very long chain fatty acid elongase 7 (EC 2.3....,281,0,NaN,NaN,0,NaN,NaN
8,A1X283,SH3 and PX domain-containing protein 2B (Adapt...,911,0,NaN,NaN,0,NaN,NaN
9,A2A2Y4,FERM domain-containing protein 3 (Band 4.1-lik...,597,0,NaN,NaN,0,NaN,NaN
10,A2RU14,Transmembrane protein 218,115,0,NaN,NaN,0,NaN,NaN
11,A4D1B5,Gamma-secretase-activating protein (GSAP) (Pro...,854,0,NaN,NaN,0,NaN,NaN
12,A4GXA9,Probable crossover junction endonuclease EME2 ...,379,0,NaN,NaN,0,NaN,NaN
13,A5D8V7,Outer dynein arm-docking complex subunit 3 (Co...,595,0,NaN,NaN,0,NaN,NaN
14,A5PLL7,Plasmanylethanolamine desaturase 1 (EC 1.14.19...,270,0,NaN,NaN,0,NaN,NaN
15,A6BM72,Multiple epidermal growth factor-like domains ...,1044,1,1.0,19.0,0,NaN,NaN
16,A6H8Y1,Transcription factor TFIIIB component B'' homo...,2624,0,NaN,NaN,0,NaN,NaN
17,A6NCS4,Homeobox protein Nkx-2.6 (Homeobox protein NK-...,301,0,NaN,NaN,0,NaN,NaN
18,A6NFY7,"Succinate dehydrogenase assembly factor 1, mit...",115,0,NaN,NaN,0,NaN,NaN
19,A6NGG8,Photoreceptor cilium actin regulator,1288,0,NaN,NaN,0,NaN,NaN
20,A6NI61,Protein myomaker (Myoblast fusion maker) (Tran...,221,0,NaN,NaN,0,NaN,NaN
21,A6NKB5,Pecanex-like protein 2 (Pecanex homolog protei...,2137,0,NaN,NaN,0,NaN,NaN
22,A6NNB3,Interferon-induced transmembrane protein 5 (Bo...,132,0,NaN,NaN,0,NaN,NaN
23,A7MD48,Serine/arginine repetitive matrix protein 4 (M...,611,0,NaN,NaN,0,NaN,NaN
24,A7XYQ1,Sine oculis-binding protein homolog (Jackson c...,873,0,NaN,NaN,0,NaN,NaN
25,A8MQ03,Cysteine-rich tail protein 1,144,0,NaN,NaN,0,NaN,NaN
26,A8MW99,Meiosis-specific protein MEI4,385,0,NaN,NaN,0,NaN,NaN
27,A9UHW6,MIF4G domain-containing protein (SLBP-interact...,222,0,NaN,NaN,0,NaN,NaN
28,B1AK53,Espin (Autosomal recessive deafness type 36 pr...,854,0,NaN,NaN,0,NaN,NaN
29,B3KU38,IQCJ-SCHIP1 readthrough transcript protein,563,0,NaN,NaN,0,NaN,NaN
30,B6A8C7,"T-cell-interacting, activating receptor on mye...",271,1,1.0,16.0,0,NaN,NaN
31,B7U540,Inward rectifier potassium channel 18 (Inward ...,433,0,NaN,NaN,0,NaN,NaN
32,C9JLW8,Mapk-regulated corepressor-interacting protein...,97,0,NaN,NaN,0,NaN,NaN
33,C9JRZ8,Aldo-keto reductase family 1 member B15 (EC 1....,316,0,NaN,NaN,0,NaN,NaN
34,D3W0D1,Killer cell lectin-like receptor subfamily F m...,207,0,NaN,NaN,0,NaN,NaN
35,E0CX11,Short transmembrane mitochondrial protein 1,47,0,NaN,NaN,0,NaN,NaN
36,O00116,"Alkyldihydroxyacetonephosphate synthase, perox...",658,0,NaN,NaN,1,1.0,58.0
37,O00161,Synaptosomal-associated protein 23 (SNAP-23) (...,211,0,NaN,NaN,0,NaN,NaN
38,O00168,Phospholemman (FXYD domain-containing ion tran...,92,1,1.0,20.0,0,NaN,NaN
39,O00214,Galectin-8 (Gal-8) (Po66 carbohydrate-binding ...,317,0,NaN,NaN,0,NaN,NaN

In [60]:
# Exploratory analysis

# Calculate total number of proteins with signal peptides
print(f"Proteins with signal peptides: {(features_df['signal_peptide'] == 1).sum()}")

# Calculate average length of all signal peptides
if features_df['signal_peptide'].sum() > 0:
    signal_lengths = features_df.loc[features_df['signal_peptide'] == 1, 'signal_end'] - \
                    features_df.loc[features_df['signal_peptide'] == 1, 'signal_start'] + 1
    print(f"Average signal peptide length: {signal_lengths.mean():.1f} amino acids")

# Check if all signal peptides start at amino acid 1
all_signal_start_ones = features_df['signal_start'].dropna().all()
print(f"All signal peptides start at amino acid 1: {all_signal_start_ones}")

# Calculate total number of proteins with transit peptides
print(f"Proteins with transit peptides: {(features_df['transit_peptide'] == 1).sum()}")

# Calculate average length of all transit peptides
if features_df['transit_peptide'].sum() > 0:
    transit_lengths = features_df.loc[features_df['transit_peptide'] == 1, 'transit_end'] - \
                     features_df.loc[features_df['transit_peptide'] == 1, 'transit_start'] + 1
    print(f"Average transit peptide length: {transit_lengths.mean():.1f} amino acids")

# Check if all transit peptides start at amino acid 1
all_transit_start_ones = features_df['transit_start'].dropna().all()
print(f"All transit peptides start at amino acid 1: {all_signal_start_ones}")

# Calculate total number of proteins with both signal and transit peptides
proteins_with_both = features_df[(features_df['signal_peptide'] == 1) & (features_df['transit_peptide'] == 1)]
print(f"Proteins with both signal and transit peptides: {len(proteins_with_both)}")

Proteins with signal peptides: 3611
Average signal peptide length: 24.1 amino acids
All signal peptides start at amino acid 1: True
Proteins with transit peptides: 562
Average transit peptide length: 37.6 amino acids
All transit peptides start at amino acid 1: True
Proteins with both signal and transit peptides: 0

## Get data for **models** and explore it

Start by using the UniProt IDs stored in the protein_IDs dictionary. Using the UniProt API, extract all information regarding the protein models available for each protein and append this information into a separate dataframe. Then analyse this further to completely understand our data i.e. how many proteins do not have any models, only Alphafold, etc.

### Get PDB informations
 #### Process each PDB_model into -> {'Source':model_source,'ID':model_id,'Method':model_method,'Resolution':model_resol,'Chains':model_chains}

In [ ]:
# Set parameters
batch_size = 500 # it will retrieve entries in groups of 500 (can change)
base_url = "https://rest.uniprot.org/uniprotkb/search"
re_next_link = re.compile(r'<(.+)>; rel="next"')

# Set up session with retry strategy
session = requests.Session()
retry_strategy = requests.adapters.Retry(
    total=5, backoff_factor=0.25, status_forcelist=[500, 502, 503, 504] # these are the codes for failed attempts
)
session.mount("https://", requests.adapters.HTTPAdapter(max_retries=retry_strategy))

# Construct query parameters (explicitly requesting only the necessary fields)
params = {
    'query': '(reviewed:true) AND (organism_id:9606)',  # 9606 is the taxonomy ID for humans
    'format': 'json',
    'fields': 'accession,structure_3d',
    'size': batch_size
}

# Construct initial URL
url = f"{base_url}?{'&'.join(f'{k}={v}' for k, v in params.items())}"

# Initialize dictionary to store protein data
uniprot_IDs = {}

models = {}
model_count = {}

progress = 0

# Start timer for total time
start_time = time.time()

# Fetch and process batches
while url:
    try:
        # Send request and get response
        response = session.get(url)
        response.raise_for_status()

        # Parse the response
        databases = response.json()['results'] #len(database) = batch_size

        # Process the data (skip header)
        for database in databases:
            uniprot_id = database['primaryAccession']
            model_DBs = database['uniProtKBCrossReferences']
            PDBs = []

            for DB in model_DBs: #each model in model_db:
                model_source, model_id, model_prop = DB['database'], DB['id'], DB['properties']

                model_method = [item for item in model_prop if item.get('key') == 'Method'][0]['value']
                model_resol = [item for item in model_prop if item.get('key') == 'Resolution'][0]['value']
                model_chains = [item for item in model_prop if item.get('key') == 'Chains'][0]['value']

                model_info = {'Source':model_source,
                              'ID':model_id,
                              'Method':model_method,
                              'Resolution':model_resol,
                              'Chains':model_chains}
                PDBs.append(model_info)

            uniprot_IDs[uniprot_id] = uniprot_id

            models[uniprot_id] = PDBs
            model_count[uniprot_id] = len(model_DBs)

        # Update progress
        progress += len(databases)
        total = response.headers.get("x-total-results", "unknown")
        print(f"Progress: {progress:,} / {int(total):,} entries",
              f"({progress/int(total)*100:.1f}%)")

        # Extract the next page URL from headers (pagination)
        next_link = response.headers.get("Link")
        if next_link:
            match = re.search(r'<(.+)>; rel="next"', next_link)
            url = match.group(1) if match else None
        else:
            url = None

    except requests.exceptions.RequestException as e:
        print(f"Error fetching batch: {e}")
        break

# Calculate and print total time
duration = time.time() - start_time
print(f"\nDownload completed in {duration:.1f} seconds")
print(f"Total entries: {len(uniprot_IDs)}")

Progress: 500 / 20,417 entries (2.4%)
Progress: 1,000 / 20,417 entries (4.9%)
Progress: 1,500 / 20,417 entries (7.3%)
Progress: 2,000 / 20,417 entries (9.8%)
Progress: 2,500 / 20,417 entries (12.2%)
Progress: 3,000 / 20,417 entries (14.7%)
Progress: 3,500 / 20,417 entries (17.1%)
Progress: 4,000 / 20,417 entries (19.6%)
Progress: 4,500 / 20,417 entries (22.0%)
Progress: 5,000 / 20,417 entries (24.5%)
Progress: 5,500 / 20,417 entries (26.9%)
Progress: 6,000 / 20,417 entries (29.4%)
Progress: 6,500 / 20,417 entries (31.8%)
Progress: 7,000 / 20,417 entries (34.3%)
Progress: 7,500 / 20,417 entries (36.7%)
Progress: 8,000 / 20,417 entries (39.2%)
Progress: 8,500 / 20,417 entries (41.6%)
Progress: 9,000 / 20,417 entries (44.1%)
Progress: 9,500 / 20,417 entries (46.5%)
Progress: 10,000 / 20,417 entries (49.0%)
Progress: 10,500 / 20,417 entries (51.4%)
Progress: 11,000 / 20,417 entries (53.9%)
Progress: 11,500 / 20,417 entries (56.3%)
Progress: 12,000 / 20,417 entries (58.8%)
Progress: 12,500 / 20,417 entries (61.2%)
Progress: 13,000 / 20,417 entries (63.7%)
Progress: 13,500 / 20,417 entries (66.1%)
Progress: 14,000 / 20,417 entries (68.6%)
Progress: 14,500 / 20,417 entries (71.0%)
Progress: 15,000 / 20,417 entries (73.5%)
Progress: 15,500 / 20,417 entries (75.9%)
Progress: 16,000 / 20,417 entries (78.4%)
Progress: 16,500 / 20,417 entries (80.8%)
Progress: 17,000 / 20,417 entries (83.3%)
Progress: 17,500 / 20,417 entries (85.7%)
Progress: 18,000 / 20,417 entries (88.2%)
Progress: 18,500 / 20,417 entries (90.6%)
Progress: 19,000 / 20,417 entries (93.1%)
Progress: 19,500 / 20,417 entries (95.5%)
Progress: 20,000 / 20,417 entries (98.0%)
Progress: 20,417 / 20,417 entries (100.0%)

Download completed in 117.9 seconds
Total entries: 20417

#### Data

In [ ]:
models

{'A0A0C5B5G6': [],
 'A0A1B0GTW7': [],
 'A0JNW5': [],
 'A0JP26': [],
 'A0PK11': [],
 'A1A4S6': [{'Source': 'PDB',
   'ID': '2MIO',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=728-786'}],
 'A1A519': [],
 'A1L190': [{'Source': 'PDB',
   'ID': '6H86',
   'Method': 'X-ray',
   'Resolution': '1.90 A',
   'Chains': 'A/B=1-88'}],
 'A1L3X0': [{'Source': 'PDB',
   'ID': '6Y7F',
   'Method': 'X-ray',
   'Resolution': '2.05 A',
   'Chains': 'A/B=1-281'}],
 'A1X283': [],
 'A2A2Y4': [],
 'A2RU14': [],
 'A2RUB6': [],
 'A2RUC4': [{'Source': 'PDB',
   'ID': '3AL5',
   'Method': 'X-ray',
   'Resolution': '2.50 A',
   'Chains': 'A/B/C/D=1-315'},
  {'Source': 'PDB',
   'ID': '3AL6',
   'Method': 'X-ray',
   'Resolution': '2.80 A',
   'Chains': 'A/B/C/D=1-315'}],
 'A4D1B5': [],
 'A4GXA9': [{'Source': 'PDB',
   'ID': '7F6L',
   'Method': 'X-ray',
   'Resolution': '3.20 A',
   'Chains': 'B=1-379'}],
 'A5D8V7': [{'Source': 'PDB',
   'ID': '8J07',
   'Method': 'EM',
   'Resolution': '4.10 A',
   'Chains': 'm8/o8/q8/s8/u8=1-595'}],
 'A5PLL7': [],
 'A6BM72': [],
 'A6H8Y1': [{'Source': 'PDB',
   'ID': '5N9G',
   'Method': 'X-ray',
   'Resolution': '2.70 A',
   'Chains': 'C/H=241-396'},
  {'Source': 'PDB',
   'ID': '8ITY',
   'Method': 'EM',
   'Resolution': '3.90 A',
   'Chains': 'W=1-2624'},
  {'Source': 'PDB',
   'ID': '8IUE',
   'Method': 'EM',
   'Resolution': '4.10 A',
   'Chains': 'W=1-2624'},
  {'Source': 'PDB',
   'ID': '8IUH',
   'Method': 'EM',
   'Resolution': '3.40 A',
   'Chains': 'W=1-2624'}],
 'A6NCS4': [],
 'A6NFY7': [],
 'A6NGG8': [{'Source': 'PDB',
   'ID': '7LXF',
   'Method': 'X-ray',
   'Resolution': '1.65 A',
   'Chains': 'A=813-848'}],
 'A6NI61': [],
 'A6NKB5': [],
 'A6NNB3': [],
 'A7E2V4': [],
 'A7MCY6': [],
 'A7MD48': [],
 'A7XYQ1': [],
 'A8MQ03': [],
 'A8MW99': [],
 'A9UHW6': [],
 'B1AK53': [],
 'B2RUY7': [],
 'B3KU38': [],
 'B6A8C7': [],
 'B7U540': [],
 'C9JLW8': [],
 'C9JRZ8': [],
 'D3W0D1': [{'Source': 'PDB',
   'ID': '4IOP',
   'Method': 'X-ray',
   'Resolution': '3.20 A',
   'Chains': 'B=63-207'}],
 'E0CX11': [],
 'O00115': [],
 'O00116': [],
 'O00159': [{'Source': 'PDB',
   'ID': '4BYF',
   'Method': 'X-ray',
   'Resolution': '2.74 A',
   'Chains': 'A/C=36-760'}],
 'O00161': [{'Source': 'PDB',
   'ID': '1NHL',
   'Method': 'X-ray',
   'Resolution': '2.30 A',
   'Chains': 'A=23-76'},
  {'Source': 'PDB',
   'ID': '3ZUS',
   'Method': 'X-ray',
   'Resolution': '2.95 A',
   'Chains': 'A/B/C/D=150-211'}],
 'O00165': [],
 'O00168': [{'Source': 'PDB',
   'ID': '2JO1',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=21-92'}],
 'O00214': [{'Source': 'PDB',
   'ID': '2YRO',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=176-317'},
  {'Source': 'PDB',
   'ID': '2YV8',
   'Method': 'X-ray',
   'Resolution': '1.92 A',
   'Chains': 'A=1-152'},
  {'Source': 'PDB',
   'ID': '2YXS',
   'Method': 'X-ray',
   'Resolution': '2.13 A',
   'Chains': 'A=1-152'},
  {'Source': 'PDB',
   'ID': '3AP4',
   'Method': 'X-ray',
   'Resolution': '2.33 A',
   'Chains': 'A/B/C/D=1-154'},
  {'Source': 'PDB',
   'ID': '3AP5',
   'Method': 'X-ray',
   'Resolution': '1.92 A',
   'Chains': 'A=1-154'},
  {'Source': 'PDB',
   'ID': '3AP6',
   'Method': 'X-ray',
   'Resolution': '1.58 A',
   'Chains': 'A/B/C/D=1-154'},
  {'Source': 'PDB',
   'ID': '3AP7',
   'Method': 'X-ray',
   'Resolution': '1.53 A',
   'Chains': 'A=1-154'},
  {'Source': 'PDB',
   'ID': '3AP9',
   'Method': 'X-ray',
   'Resolution': '1.33 A',
   'Chains': 'A=1-154'},
  {'Source': 'PDB',
   'ID': '3APB',
   'Method': 'X-ray',
   'Resolution': '1.95 A',
   'Chains': 'A/B=1-154'},
  {'Source': 'PDB',
   'ID': '3OJB',
   'Method': 'X-ray',
   'Resolution': '3.01 A',
   'Chains': 'A/B/C/D=186-315'},
  {'Source': 'PDB',
   'ID': '3VKL',
   'Method': 'X-ray',
   'Resolution': '2.55 A',
   'Chains': 'A/B=1-155, A/B=184-317'},
  {'Source': 'PDB',
   'ID': '3VKM',
   'Method': 'X-ray',
   'Resolution': '2.98 A',
   'Chains': 'A/B=1-155, A/B=184-317'},
  {'Source': 'PDB',
   'ID': '3VKN',
   'Method': 'X-ray',
   'Resolution': '1.98 A',
   'Chains': 'A/B=1-153'},
  {'Source': 'PDB',
   'ID': '3VKO',
   'Method': 'X-ray',
   'Resolution': '2.08 A',
   'Chains': 'A/B=1-153'},
  {'Source': 'PDB',
   'ID': '4BMB',
   'Method': 'X-ray',
   'Resolution': '1.35 A',
   'Chains': 'A=4-153'},
  {'Source': 'PDB',
   'ID': '4BME',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A/B=4-155'},
  {'Source': 'PDB',
   'ID': '4FQZ',
   'Method': 'X-ray',
   'Resolution': '2.80 A',
   'Chains': 'A=1-155, A=184-317'},
  {'Source': 'PDB',
   'ID': '4GXL',
   'Method': 'X-ray',
   'Resolution': '2.02 A',
   'Chains': 'A=186-317'},
  {'Source': 'PDB',
   'ID': '4HAN',
   'Method': 'X-ray',
   'Resolution': '2.55 A',
   'Chains': 'A/B=1-155, A/B=184-317'},
  {'Source': 'PDB',
   'ID': '5GZC',
   'Method': 'X-ray',
   'Resolution': '1.08 A',
   'Chains': 'A=7-158'},
  {'Source': 'PDB',
   'ID': '5GZD',
   'Method': 'X-ray',
   'Resolution': '1.19 A',
   'Chains': 'A=7-154'},
  {'Source': 'PDB',
   'ID': '5GZE',
   'Method': 'X-ray',
   'Resolution': '1.32 A',
   'Chains': 'A=7-154'},
  {'Source': 'PDB',
   'ID': '5GZF',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A=1-186'},
  {'Source': 'PDB',
   'ID': '5GZG',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A=1-186'},
  {'Source': 'PDB',
   'ID': '5T7I',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A=1-155'},
  {'Source': 'PDB',
   'ID': '5T7S',
   'Method': 'X-ray',
   'Resolution': '1.90 A',
   'Chains': 'A=1-155'},
  {'Source': 'PDB',
   'ID': '5T7T',
   'Method': 'X-ray',
   'Resolution': '1.96 A',
   'Chains': 'A=1-155'},
  {'Source': 'PDB',
   'ID': '5T7U',
   'Method': 'X-ray',
   'Resolution': '1.58 A',
   'Chains': 'A=1-155'},
  {'Source': 'PDB',
   'ID': '5VWG',
   'Method': 'X-ray',
   'Resolution': '2.10 A',
   'Chains': 'A=1-155'},
  {'Source': 'PDB',
   'ID': '6W4Z',
   'Method': 'X-ray',
   'Resolution': '1.59 A',
   'Chains': 'A/B=2-154'},
  {'Source': 'PDB',
   'ID': '6Z6Y',
   'Method': 'X-ray',
   'Resolution': '1.34 A',
   'Chains': 'A=1-163'},
  {'Source': 'PDB',
   'ID': '7AEN',
   'Method': 'X-ray',
   'Resolution': '1.60 A',
   'Chains': 'A/B=7-156'},
  {'Source': 'PDB',
   'ID': '7ALS',
   'Method': 'X-ray',
   'Resolution': '1.35 A',
   'Chains': 'A/B=4-158'},
  {'Source': 'PDB',
   'ID': '7P1M',
   'Method': 'X-ray',
   'Resolution': '1.52 A',
   'Chains': 'A/B=6-156'},
  {'Source': 'PDB',
   'ID': '8CM8',
   'Method': 'X-ray',
   'Resolution': '1.22 A',
   'Chains': 'A/B=1-317'},
  {'Source': 'PDB',
   'ID': '8HL9',
   'Method': 'X-ray',
   'Resolution': '1.60 A',
   'Chains': 'A=171-317'}],
 'O00237': [],
 'O00254': [],
 'O00268': [{'Source': 'PDB',
   'ID': '1H3O',
   'Method': 'X-ray',
   'Resolution': '2.30 A',
   'Chains': 'A/C=872-945'},
  {'Source': 'PDB',
   'ID': '2P6V',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A=575-688'},
  {'Source': 'PDB',
   'ID': '6MZC',
   'Method': 'EM',
   'Resolution': '4.50 A',
   'Chains': 'E=1-1085'},
  {'Source': 'PDB',
   'ID': '6MZD',
   'Method': 'EM',
   'Resolution': '9.80 A',
   'Chains': 'D=1-1085'},
  {'Source': 'PDB',
   'ID': '6MZL',
   'Method': 'EM',
   'Resolution': '23.00 A',
   'Chains': 'D/E=1-1085'},
  {'Source': 'PDB',
   'ID': '6MZM',
   'Method': 'EM',
   'Resolution': '7.50 A',
   'Chains': 'D=61-1085'},
  {'Source': 'PDB',
   'ID': '7EDX',
   'Method': 'EM',
   'Resolution': '4.50 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EG7',
   'Method': 'EM',
   'Resolution': '6.20 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EG8',
   'Method': 'EM',
   'Resolution': '7.40 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EG9',
   'Method': 'EM',
   'Resolution': '3.70 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGA',
   'Method': 'EM',
   'Resolution': '4.10 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGB',
   'Method': 'EM',
   'Resolution': '3.30 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGC',
   'Method': 'EM',
   'Resolution': '3.90 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGD',
   'Method': 'EM',
   'Resolution': '6.75 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGE',
   'Method': 'EM',
   'Resolution': '9.00 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGF',
   'Method': 'EM',
   'Resolution': '3.16 A',
   'Chains': 'd=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGG',
   'Method': 'EM',
   'Resolution': '2.77 A',
   'Chains': 'D=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGI',
   'Method': 'EM',
   'Resolution': '9.82 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7EGJ',
   'Method': 'EM',
   'Resolution': '8.64 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '7ENA',
   'Method': 'EM',
   'Resolution': '4.07 A',
   'Chains': 'DD/Dd=1-1085'},
  {'Source': 'PDB',
   'ID': '7ENC',
   'Method': 'EM',
   'Resolution': '4.13 A',
   'Chains': 'DD/Dd=1-1085'},
  {'Source': 'PDB',
   'ID': '8GXQ',
   'Method': 'EM',
   'Resolution': '5.04 A',
   'Chains': 'DD/Dd=1-1085'},
  {'Source': 'PDB',
   'ID': '8GXS',
   'Method': 'EM',
   'Resolution': '4.16 A',
   'Chains': 'DD/Dd=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAK',
   'Method': 'EM',
   'Resolution': '5.47 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAL',
   'Method': 'EM',
   'Resolution': '8.52 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAN',
   'Method': 'EM',
   'Resolution': '6.07 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAO',
   'Method': 'EM',
   'Resolution': '6.40 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAP',
   'Method': 'EM',
   'Resolution': '5.85 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAQ',
   'Method': 'EM',
   'Resolution': '6.29 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAR',
   'Method': 'EM',
   'Resolution': '7.20 A',
   'Chains': 'D/d=1-1085'},
  {'Source': 'PDB',
   'ID': '8WAS',
   'Method': 'EM',
   'Resolution': '6.13 A',
   'Chains': 'D/d=1-1085'}],
 'O00291': [{'Source': 'PDB',
   'ID': '2NO2',
   'Method': 'X-ray',
   'Resolution': '2.80 A',
   'Chains': 'A=482-586'},
  {'Source': 'PDB',
   'ID': '2QA7',
   'Method': 'X-ray',
   'Resolution': '2.80 A',
   'Chains': 'A/B/C/D=370-481'},
  {'Source': 'PDB',
   'ID': '3I00',
   'Method': 'X-ray',
   'Resolution': '2.30 A',
   'Chains': 'A/B=361-480'}],
 'O00300': [{'Source': 'PDB',
   'ID': '3URF',
   'Method': 'X-ray',
   'Resolution': '2.70 A',
   'Chains': 'Z=22-186'}],
 'O00322': [],
 'O00329': [{'Source': 'PDB',
   'ID': '5DXU',
   'Method': 'X-ray',
   'Resolution': '2.64 A',
   'Chains': 'A=2-1044'},
  {'Source': 'PDB',
   'ID': '5M6U',
   'Method': 'X-ray',
   'Resolution': '2.85 A',
   'Chains': 'A=17-1027'},
  {'Source': 'PDB',
   'ID': '5T8F',
   'Method': 'X-ray',
   'Resolution': '2.91 A',
   'Chains': 'A=17-1031'},
  {'Source': 'PDB',
   'ID': '5UBT',
   'Method': 'X-ray',
   'Resolution': '2.83 A',
   'Chains': 'A=17-1029'},
  {'Source': 'PDB',
   'ID': '5VLR',
   'Method': 'X-ray',
   'Resolution': '2.80 A',
   'Chains': 'A=17-1029'},
  {'Source': 'PDB',
   'ID': '6G6W',
   'Method': 'X-ray',
   'Resolution': '2.72 A',
   'Chains': 'A=1-1044'},
  {'Source': 'PDB',
   'ID': '6OCO',
   'Method': 'X-ray',
   'Resolution': '2.58 A',
   'Chains': 'A=17-1031'},
  {'Source': 'PDB',
   'ID': '6OCU',
   'Method': 'X-ray',
   'Resolution': '2.77 A',
   'Chains': 'A=1-1044'},
  {'Source': 'PDB',
   'ID': '6PYR',
   'Method': 'X-ray',
   'Resolution': '2.21 A',
   'Chains': 'A=17-1034'},
  {'Source': 'PDB',
   'ID': '6PYU',
   'Method': 'X-ray',
   'Resolution': '2.54 A',
   'Chains': 'A=17-1034'},
  {'Source': 'PDB',
   'ID': '7JIS',
   'Method': 'X-ray',
   'Resolution': '2.42 A',
   'Chains': 'A=17-1034'},
  {'Source': 'PDB',
   'ID': '7LM2',
   'Method': 'X-ray',
   'Resolution': '2.79 A',
   'Chains': 'A=12-1031'},
  {'Source': 'PDB',
   'ID': '7LQ1',
   'Method': 'X-ray',
   'Resolution': '2.96 A',
   'Chains': 'A=1-1044'},
  {'Source': 'PDB',
   'ID': '8BCY',
   'Method': 'X-ray',
   'Resolution': '2.43 A',
   'Chains': 'A=17-1034'},
  {'Source': 'PDB',
   'ID': '8S3R',
   'Method': 'X-ray',
   'Resolution': '2.28 A',
   'Chains': 'A=17-1034'}],
 'O00330': [{'Source': 'PDB',
   'ID': '1ZY8',
   'Method': 'X-ray',
   'Resolution': '2.59 A',
   'Chains': 'K/L/M/N/O=54-274'},
  {'Source': 'PDB',
   'ID': '2DNC',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=57-141'},
  {'Source': 'PDB',
   'ID': '2F5Z',
   'Method': 'X-ray',
   'Resolution': '2.18 A',
   'Chains': 'K/L/M/N/O=173-228'},
  {'Source': 'PDB',
   'ID': '2F60',
   'Method': 'X-ray',
   'Resolution': '1.55 A',
   'Chains': 'K=173-228'},
  {'Source': 'PDB',
   'ID': '6H60',
   'Method': 'EM',
   'Resolution': '6.00 A',
   'Chains': 'A=1-501'}],
 'O00337': [],
 'O00400': [],
 'O00409': [{'Source': 'PDB',
   'ID': '6NCE',
   'Method': 'X-ray',
   'Resolution': '2.60 A',
   'Chains': 'A=112-210'},
  {'Source': 'PDB',
   'ID': '6NCM',
   'Method': 'X-ray',
   'Resolution': '2.70 A',
   'Chains': 'A/B=112-210'}],
 'O00422': [{'Source': 'PDB',
   'ID': '2HDE',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=6-149'}],
 'O00444': [{'Source': 'PDB',
   'ID': '2N19',
   'Method': 'NMR',
   'Resolution': '-',
   'Chains': 'A=884-970'},
  {'Source': 'PDB',
   'ID': '3COK',
   'Method': 'X-ray',
   'Resolution': '2.25 A',
   'Chains': 'A/B=2-275'},
  {'Source': 'PDB',
   'ID': '4JXF',
   'Method': 'X-ray',
   'Resolution': '2.40 A',
   'Chains': 'A=4-269'},
  {'Source': 'PDB',
   'ID': '4N7V',
   'Method': 'X-ray',
   'Resolution': '2.76 A',
   'Chains': 'A/B=580-808'},
  {'Source': 'PDB',
   'ID': '4N7Z',
   'Method': 'X-ray',
   'Resolution': '2.85 A',
   'Chains': 'A=580-808'},
  {'Source': 'PDB',
   'ID': '4N9J',
   'Method': 'X-ray',
   'Resolution': '2.60 A',
   'Chains': 'A/B=581-808'},
  {'Source': 'PDB',
   'ID': '4YUR',
   'Method': 'X-ray',
   'Resolution': '2.65 A',
   'Chains': 'A=2-275'},
  {'Source': 'PDB',
   'ID': '4YYP',
   'Method': 'X-ray',
   'Resolution': '2.60 A',
   'Chains': 'A=884-970'},
  {'Source': 'PDB',
   'ID': '5LHY',
   'Method': 'X-ray',
   'Resolution': '3.31 A',
   'Chains': '1/2/3/4/5/6/7/8/9/A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U=884-970'},
  {'Source': 'PDB',
   'ID': '5LHZ',
   'Method': 'X-ray',
   'Resolution': '2.51 A',
   'Chains': 'A/B/C=884-970'},
  {'Source': 'PDB',
   'ID': '6N45',
   'Method': 'X-ray',
   'Resolution': '2.64 A',
   'Chains': 'A/B=581-808'},
  {'Source': 'PDB',
   'ID': '6N46',
   'Method': 'X-ray',
   'Resolution': '3.71 A',
   'Chains': 'A/B/C/D/E/F/G/H=581-808'},
  {'Source': 'PDB',
   'ID': '6W38',
   'Method': 'X-ray',
   'Resolution': '4.48 A',
   'Chains': 'B=585-807'},
  {'Source': 'PDB',
   'ID': '6W3I',
   'Method': 'X-ray',
   'Resolution': '3.80 A',
   'Chains': 'B=585-807'},
  {'Source': 'PDB',
   'ID': '6W3J',
   'Method': 'X-ray',
   'Resolution': '4.38 A',
   'Chains': 'B=585-807'},
  {'Source': 'PDB',
   'ID': '8XPG',
   'Method': 'X-ray',
   'Resolution': '2.70 A',
   'Chains': 'A/B=581-808'}],
 'O00453': [],
 'O00462': [],
 'O00478': [{'Source': 'PDB',
   'ID': '4F8T',
   'Method': 'X-ray',
   'Resolution': '2.38 A',
   'Chains': 'A=30-246'},
  {'Source': 'PDB',
   'ID': '5ZZ3',
   'Method': 'X-ray',
   'Resolution': '3.00 A',
   'Chains': 'A=328-584'},
  {'Source': 'PDB',
   'ID': '6J0G',
   'Method': 'X-ray',
   'Resolution': '1.60 A',
   'Chains': 'A/B/C/D=328-515'},
  {'Source': 'PDB',
   'ID': '6J0K',
   'Method': 'X-ray',
   'Resolution': '2.00 A',
   'Chains': 'A/B=328-515'},
  {'Source': 'PDB',
   'ID': '6J0L',
   'Method': 'X-ray',
   'Resolution': '1.95 A',
   'Chains': 'A/B=328-515'}],
 'O00487': [{'Source': 'PDB',
   'ID': '5GJQ',
   'Method': 'EM',
   'Resolution': '4.50 A',
   'Chains': 'V=1-310'},
  {'Source': 'PDB',
   'ID': '5GJR',
   'Method': 'EM',
   'Resolution': '3.50 A',
   'Chains': '9/V=1-310'},
  {'Source': 'PDB',
   'ID': '5L4K',
   'Method': 'EM',
   'Resolution': '4.50 A',
   'Chains': 'V=1-310'},
  {'Source': 'PDB',
   'ID': '5LN3',
   'Method': 'EM',
   'Resolution': '6.80 A',
   'Chains': 'V=1-310'},
  {'Source': 'PDB',
   'ID': '5M32',
   'Method': 'EM',
   'Resolution': '3.80 A',
   'Chains': 'q=1-310'},
  {'Source': 'PDB',
   'ID': '5T0C',
   'Method': 'EM',
   'Resolution': '3.80 A',
   'Chains': 'Ac/Bc=1-310'},
  {'Source': 'PDB',
   'ID': '5T0G',
   'Method': 'EM',
   'Resolution': '4.40 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '5T0H',
   'Method': 'EM',
   'Resolution': '6.80 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '5T0I',
   'Method': 'EM',
   'Resolution': '8.00 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '5T0J',
   'Method': 'EM',
   'Resolution': '8.00 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '5VFP',
   'Method': 'EM',
   'Resolution': '4.20 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VFQ',
   'Method': 'EM',
   'Resolution': '4.20 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VFR',
   'Method': 'EM',
   'Resolution': '4.90 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VFS',
   'Method': 'EM',
   'Resolution': '3.60 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '5VFT',
   'Method': 'EM',
   'Resolution': '7.00 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VFU',
   'Method': 'EM',
   'Resolution': '5.80 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VGZ',
   'Method': 'EM',
   'Resolution': '3.70 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VHF',
   'Method': 'EM',
   'Resolution': '5.70 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VHH',
   'Method': 'EM',
   'Resolution': '6.10 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VHI',
   'Method': 'EM',
   'Resolution': '6.80 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '5VHS',
   'Method': 'EM',
   'Resolution': '8.80 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '6MSB',
   'Method': 'EM',
   'Resolution': '3.00 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSD',
   'Method': 'EM',
   'Resolution': '3.20 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSE',
   'Method': 'EM',
   'Resolution': '3.30 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSG',
   'Method': 'EM',
   'Resolution': '3.50 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSH',
   'Method': 'EM',
   'Resolution': '3.60 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSJ',
   'Method': 'EM',
   'Resolution': '3.30 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6MSK',
   'Method': 'EM',
   'Resolution': '3.20 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6WJD',
   'Method': 'EM',
   'Resolution': '4.80 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '6WJN',
   'Method': 'EM',
   'Resolution': '5.70 A',
   'Chains': 'c=24-310'},
  {'Source': 'PDB',
   'ID': '7QXN',
   'Method': 'EM',
   'Resolution': '3.70 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QXP',
   'Method': 'EM',
   'Resolution': '3.60 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QXU',
   'Method': 'EM',
   'Resolution': '4.30 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QXW',
   'Method': 'EM',
   'Resolution': '4.10 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QXX',
   'Method': 'EM',
   'Resolution': '4.40 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QY7',
   'Method': 'EM',
   'Resolution': '4.70 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QYA',
   'Method': 'EM',
   'Resolution': '4.80 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',
   'ID': '7QYB',
   'Method': 'EM',
   'Resolution': '4.10 A',
   'Chains': 'c=2-310'},
  {'Source': 'PDB',

In [ ]:
model_count

{'A0A0C5B5G6': 0,
 'A0A1B0GTW7': 0,
 'A0JNW5': 0,
 'A0JP26': 0,
 'A0PK11': 0,
 'A1A4S6': 1,
 'A1A519': 0,
 'A1L190': 1,
 'A1L3X0': 1,
 'A1X283': 0,
 'A2A2Y4': 0,
 'A2RU14': 0,
 'A2RUB6': 0,
 'A2RUC4': 2,
 'A4D1B5': 0,
 'A4GXA9': 1,
 'A5D8V7': 1,
 'A5PLL7': 0,
 'A6BM72': 0,
 'A6H8Y1': 4,
 'A6NCS4': 0,
 'A6NFY7': 0,
 'A6NGG8': 1,
 'A6NI61': 0,
 'A6NKB5': 0,
 'A6NNB3': 0,
 'A7E2V4': 0,
 'A7MCY6': 0,
 'A7MD48': 0,
 'A7XYQ1': 0,
 'A8MQ03': 0,
 'A8MW99': 0,
 'A9UHW6': 0,
 'B1AK53': 0,
 'B2RUY7': 0,
 'B3KU38': 0,
 'B6A8C7': 0,
 'B7U540': 0,
 'C9JLW8': 0,
 'C9JRZ8': 0,
 'D3W0D1': 1,
 'E0CX11': 0,
 'O00115': 0,
 'O00116': 0,
 'O00159': 1,
 'O00161': 2,
 'O00165': 0,
 'O00168': 1,
 'O00214': 36,
 'O00237': 0,
 'O00254': 0,
 'O00268': 31,
 'O00291': 3,
 'O00300': 1,
 'O00322': 0,
 'O00329': 15,
 'O00330': 5,
 'O00337': 0,
 'O00400': 0,
 'O00409': 2,
 'O00422': 1,
 'O00444': 16,
 'O00453': 0,
 'O00462': 0,
 'O00478': 5,
 'O00487': 52,
 'O00505': 0,
 'O00506': 4,
 'O00507': 0,
 'O00560': 55,
 'O00591': 0,
 'O00622': 2,
 'O00624': 0,
 'O00635': 0,
 'O00712': 0,
 'O00746': 1,
 'O00748': 0,
 'O00762': 7,
 'O14497': 3,
 'O14503': 0,
 'O14508': 13,
 'O14519': 1,
 'O14524': 0,
 'O14548': 0,
 'O14561': 36,
 'O14613': 0,
 'O14618': 7,
 'O14628': 0,
 'O14638': 2,
 'O14640': 3,
 'O14654': 0,
 'O14657': 0,
 'O14744': 65,
 'O14756': 0,
 'O14757': 160,
 'O14763': 13,
 'O14788': 2,
 'O14804': 0,
 'O14813': 0,
 'O14843': 2,
 'O14907': 9,
 'O14908': 0,
 'O14910': 0,
 'O14925': 0,
 'O14926': 0,
 'O14933': 8,
 'O14939': 6,
 'O14949': 3,
 'O14958': 4,
 'O14960': 3,
 'O14967': 0,
 'O14975': 0,
 'O14979': 1,
 'O14994': 1,
 'O15067': 0,
 'O15078': 0,
 'O15111': 5,
 'O15116': 0,
 'O15119': 1,
 'O15120': 0,
 'O15127': 0,
 'O15156': 0,
 'O15162': 1,
 'O15169': 20,
 'O15230': 2,
 'O15232': 0,
 'O15245': 16,
 'O15247': 3,
 'O15259': 2,
 'O15260': 0,
 'O15263': 5,
 'O15265': 4,
 'O15266': 0,
 'O15269': 17,
 'O15297': 1,
 'O15318': 13,
 'O15370': 0,
 'O15389': 3,
 'O15399': 6,
 'O15400': 0,
 'O15446': 7,
 'O15484': 1,
 'O15488': 1,
 'O15511': 2,
 'O15520': 1,
 'O15533': 7,
 'O15540': 8,
 'O15541': 11,
 'O15551': 0,
 'O15554': 4,
 'O42043': 0,
 'O43143': 6,
 'O43155': 0,
 'O43166': 0,
 'O43172': 25,
 'O43181': 4,
 'O43196': 0,
 'O43237': 14,
 'O43264': 1,
 'O43294': 0,
 'O43310': 0,
 'O43323': 5,
 'O43395': 30,
 'O43439': 0,
 'O43464': 13,
 'O43474': 1,
 'O43521': 45,
 'O43525': 1,
 'O43526': 19,
 'O43529': 0,
 'O43543': 4,
 'O43548': 0,
 'O43556': 0,
 'O43566': 5,
 'O43581': 1,
 'O43593': 0,
 'O43598': 5,
 'O43603': 4,
 'O43609': 0,
 'O43715': 6,
 'O43719': 11,
 'O43761': 0,
 'O43763': 1,
 'O43808': 0,
 'O43818': 5,
 'O43823': 0,
 'O43825': 0,
 'O43826': 0,
 'O43827': 0,
 'O43854': 1,
 'O43865': 1,
 'O43866': 2,
 'O43868': 0,
 'O43897': 1,
 'O43903': 0,
 'O43913': 14,
 'O43914': 5,
 'O60235': 0,
 'O60264': 4,
 'O60266': 0,
 'O60281': 2,
 'O60284': 1,
 'O60307': 2,
 'O60315': 1,
 'O60381': 2,
 'O60393': 0,
 'O60449': 4,
 'O60469': 1,
 'O60481': 2,
 'O60502': 22,
 'O60519': 0,
 'O60548': 0,
 'O60568': 14,
 'O60635': 0,
 'O60636': 0,
 'O60667': 7,
 'O60678': 10,
 'O60682': 0,
 'O60687': 0,
 'O60706': 0,
 'O60729': 3,
 'O60741': 11,
 'O60759': 1,
 'O60784': 5,
 'O60814': 68,
 'O60831': 0,
 'O60879': 0,
 'O60882': 1,
 'O60884': 1,
 'O60909': 0,
 'O60921': 7,
 'O60930': 7,
 'O60938': 0,
 'O60939': 33,
 'O60941': 0,
 'O60942': 9,
 'O75019': 0,
 'O75022': 0,
 'O75072': 0,
 'O75077': 0,
 'O75132': 0,
 'O75151': 9,
 'O75159': 0,
 'O75175': 4,
 'O75177': 0,
 'O75190': 4,
 'O75191': 4,
 'O75309': 0,
 'O75319': 3,
 'O75334': 6,
 'O75339': 0,
 'O75344': 1,
 'O75365': 4,
 'O75367': 13,
 'O75369': 23,
 'O75376': 25,
 'O75379': 0,
 'O75390': 3,
 'O75396': 5,
 'O75438': 4,
 'O75443': 0,
 'O75449': 2,
 'O75469': 67,
 'O75475': 34,
 'O75486': 3,
 'O75503': 1,
 'O75554': 11,
 'O75558': 0,
 'O75564': 0,
 'O75594': 1,
 'O75610': 0,
 'O75618': 0,
 'O75628': 1,
 'O75629': 1,
 'O75638': 0,
 'O75648': 0,
 'O75674': 1,
 'O75679': 0,
 'O75683': 4,
 'O75752': 0,
 'O75762': 14,
 'O75781': 0,
 'O75807': 4,
 'O75815': 1,
 'O75821': 18,
 'O75828': 1,
 'O75838': 0,
 'O75864': 0,
 'O75879': 0,
 'O75882': 0,
 'O75884': 3,
 'O75897': 2,
 'O75928': 2,
 'O75935': 0,
 'O75952': 0,
 'O75956': 1,
 'O75969': 0,
 'O76027': 0,
 'O76039': 2,
 'O76074': 46,
 'O76075': 1,
 'O76093': 1,
 'O77932': 0,
 'O94762': 15,
 'O94768': 10,
 'O94805': 0,
 'O94808': 0,
 'O94810': 0,
 'O94818': 0,
 'O94876': 0,
 'O94889': 0,
 'O94898': 0,
 'O94901': 8,
 'O94923': 3,
 'O94964': 0,
 'O94983': 0,
 'O94985': 0,
 'O94993': 1,
 'O95047': 0,
 'O95049': 1,
 'O95125': 0,
 'O95139': 4,
 'O95153': 0,
 'O95154': 1,
 'O95155': 4,
 'O95169': 4,
 'O95208': 0,
 'O95237': 0,
 'O95248': 0,
 'O95260': 2,
 'O95274': 2,
 'O95294': 0,
 'O95298': 4,
 'O95342': 6,
 'O95343': 0,
 'O95352': 0,
 'O95361': 1,
 'O95373': 0,
 'O95393': 5,
 'O95394': 0,
 'O95415': 0,
 'O95427': 0,
 'O95429': 2,
 'O95447': 0,
 'O95466': 1,
 'O95470': 2,
 'O95479': 1,
 'O95497': 6,
 'O95528': 0,
 'O95544': 2,
 'O95571': 1,
 'O95622': 2,
 'O95630': 4,
 'O95670': 0,
 'O95674': 0,
 'O95714': 13,
 'O95741': 0,
 'O95750': 4,
 'O95758': 0,
 'O95777': 19,
 'O95782': 0,
 'O95793': 4,
 'O95807': 0,
 'O95835': 4,
 'O95843': 1,
 'O95876': 1,
 'O95881': 2,
 'O95886': 0,
 'O95905': 0,
 'O95907': 0,
 'O95944': 1,
 'O95977': 1,
 'O95990': 0,
 'O95996': 0,
 'O96000': 4,
 'O96004': 0,
 'O96005': 0,
 'P00338': 45,
 'P00374': 89,
 'P00480': 4,
 'P00505': 2,
 'P00519': 84,
 'P00846': 10,
 'P01011': 9,
 'P01185': 5,
 'P01270': 26,
 'P01275': 37,
 'P01308': 356,
 'P01571': 0,
 'P01579': 7,
 'P01597': 2,
 'P01615': 0,
 'P01732': 8,
 'P01764': 7,
 'P01877': 4,
 'P01909': 26,
 'P02452': 13,
 'P02511': 20,
 'P02538': 1,
 'P02649': 28,
 'P02679': 45,
 'P02743': 13,
 'P02745': 9,
 'P02747': 9,
 'P02748': 9,
 'P02771': 5,
 'P02774': 6,
 'P02776': 10,
 'P02786': 21,
 'P02812': 0,
 'P03915': 4,
 'P03951': 111,
 'P03956': 15,
 'P03999': 0,
 'P04062': 56,
 'P04080': 3,
 'P04090': 2,
 'P04155': 3,
 'P04179': 41,
 'P04180': 6,
 'P04198': 2,
 'P04201': 0,
 'P04275': 40,
 'P04406': 20,
 'P04626': 52,
 'P04731': 0,
 'P04844': 4,
 'P05106': 102,
 'P05177': 1,
 'P05204': 0,
 'P05362': 14,
 'P05386': 3,
 'P05451': 2,
 'P05452': 4,
 'P05787': 3,
 'P05813': 0,
 'P05814': 0,
 'P05976': 0,
 'P05997': 0,
 'P06028': 3,
 'P06126': 15,
 'P06454': 2,
 'P06734': 23,
 'P06756': 38,
 'P06865': 2,
 'P06899': 220,
 'P07197': 0,
 'P07305': 14,
 'P07359': 21,
 'P07384': 5,
 'P07438': 0,
 'P07492': 9,
 'P07510': 0,
 'P07737': 22,
 'P07902': 2,
 'P07910': 5,
 'P07942': 3,
 'P07998': 12,
 'P08172': 17,
 'P08253': 14,
 'P08519': 16,
 'P08572': 4,
 'P08620': 1,
 'P08621': 10,
 'P08637': 14,
 'P08648': 9,
 'P08670': 26,
 'P08700': 4,
 'P08865': 110,
 'P08887': 9,
 'P08922': 4,
 'P09017': 0,
 'P09038': 25,
 'P09086': 2,
 'P09466': 1,
 'P09467': 49,
 'P09493': 9,
 'P09496': 1,
 'P09525': 1,
 'P09543': 1,
 'P09544': 0,
 'P09603': 8,
 'P09668': 2,
 'P09683': 3,
 'P09758': 6,
 'P09769': 3,
 'P09848': 0,
 'P09874': 95,
 'P09884': 20,
 'P09912': 0,
 'P09914': 8,
 'P09936': 13,
 'P0C024': 38,
 'P0C0S8': 24,
 'P0C5Z0': 3,
 'P0C7P0': 1,
 'P0C870': 2,
 'P0CAP2': 1,
 'P0CG20': 0,
 'P0DI81': 0,
 'P0DI82': 0,
 'P0DI83': 0,
 'P0DMS8': 2,
 'P0DP58': 1,
 'P0DPB6': 21,
 'P0DPH7': 0,
 'P0DPK4': 0,
 'P0DTE4': 0,
 'P10153': 15,
 'P10176': 2,
 'P10276': 12,
 'P10523': 0,
 'P10619': 12,
 'P10620': 0,
 'P10632': 5,
 'P10635': 14,
 'P10645': 2,
 'P10646': 8,
 'P10721': 42,
 'P10767': 0,
 'P10909': 2,
 'P10911': 0,
 'P10916': 3,
 'P11055': 0,
 'P11137': 0,
 'P11233': 16,
 'P11308': 8,
 'P11441': 6,
 'P11464': 0,
 'P11686': 3,
 'P11766': 10,
 'P11801': 0,
 'P12004': 76,
 'P12035': 0,
 'P12036': 0,
 'P12694': 24,
 'P12814': 4,
 'P12830': 21,
 'P13051': 22,
 'P13164': 0,
 'P13284': 0,
 'P13378': 0,
 'P13473': 2,
 'P13489': 4,
 'P13591': 7,
 'P13646': 0,
 'P13647': 2,
 'P13671': 11,
 'P13686': 2,
 'P13688': 15,
 'P13716': 4,
 'P13765': 1,
 'P13866': 4,
 'P13928': 2,
 'P13994': 0,
 'P14060': 0,
 'P14136': 1,
 'P14174': 110,
 'P14317': 0,
 'P14550': 1,
 'P14649': 29,
 'P14652': 0,
 'P14678': 65,
 'P14735': 61,
 'P14784': 7,
 'P14867': 32,
 'P14920': 22,
 'P15090': 243,
 'P15104': 4,
 'P15170': 7,
 'P15260': 5,
 'P15313': 0,
 'P15374': 5,
 'P15391': 4,
 'P15428': 4,
 'P15514': 1,
 'P15529': 7,
 'P15814': 3,
 'P15848': 1,
 'P15880': 109,
 'P15923': 5,
 'P15941': 18,
 'P16112': 2,
 'P16150': 0,
 'P16234': 14,
 'P16383': 0,
 'P16389': 0,
 'P16410': 21,
 'P16455': 11,
 'P16473': 9,
 'P16591': 2,
 'P16615': 15,
 'P16870': 0,
 'P16989': 0,
 'P17022': 0,
 'P17023': 0,
 'P17040': 0,
 'P17050': 7,
 'P17096': 5,
 'P17252': 6,
 'P17405': 4,
 'P17509': 0,
 'P17540': 1,
 'P17643': 13,
 'P17676': 16,
 'P17787': 15,
 'P17812': 6,
 'P17861': 4,
 'P17947': 30,
 'P17987': 49,
 'P18074': 42,
 'P18075': 4,
 'P18084': 3,
 'P18124': 103,
 'P18440': 2,
 'P18510': 5,
 'P18621': 103,
 'P18669': 23,
 'P18848': 1,
 'P18858': 26,
 'P19021': 0,
 'P19099': 7,
 'P19113': 4,
 'P19224': 0,
 'P19367': 10,
 'P19438': 10,
 'P19484': 4,
 'P19532': 1,
 'P19634': 16,
 'P19835': 7,
 'P19875': 2,
 'P20036': 10,
 'P20061': 2,
 'P20132': 2,
 'P20292': 4,
 'P20338': 4,
 'P20618': 114,
 'P20700': 7,
 'P20794': 0,
 'P20815': 1,
 'P20823': 6,
 'P20851': 0,
 'P21127': 1,
 'P21128': 1,
 'P21359': 26,
 'P21439': 4,
 'P21583': 6,
 'P21589': 41,
 'P21675': 64,
 'P21709': 4,
 'P21728': 22,
 'P21757': 1,
 'P21796': 11,
 'P21815': 0,
 'P21860': 21,
 'P21926': 5,
 'P21980': 13,
 'P22105': 3,
 'P22303': 74,
 'P22304': 2,
 'P22307': 2,
 'P22455': 50,
 'P22492': 0,
 'P22570': 0,
 'P22674': 0,
 'P22732': 0,
 'P22735': 1,
 'P22897': 24,
 'P23083': 1,
 'P23193': 16,
 'P23409': 0,
 'P23416': 4,
 'P23458': 50,
 'P23468': 8,
 'P23786': 0,
 'P23921': 12,
 'P23942': 1,
 'P24278': 0,
 'P24666': 17,
 'P25025': 6,
 'P25098': 20,
 'P25103': 13,
 'P25106': 8,
 'P25440': 162,
 'P25445': 6,
 'P25788': 97,
 'P25874': 4,
 'P25929': 5,
 'P25940': 0,
 'P26022': 2,
 'P26038': 9,
 'P26368': 39,
 'P26439': 0,
 'P26447': 17,
 'P26639': 5,
 'P26885': 2,
 'P27037': 5,
 'P27144': 3,
 'P27338': 52,
 'P27352': 2,
 'P27449': 6,
 'P27482': 1,
 'P27539': 0,
 'P27694': 39,
 'P27695': 66,
 'P28039': 2,
 'P28069': 1,
 'P28330': 3,
 'P28335': 7,
 'P28340': 5,
 'P28347': 11,
 'P28360': 0,
 'P28370': 0,
 'P28562': 4,
 'P28698': 1,
 'P29017': 5,
 'P29034': 2,
 'P29084': 42,
 'P29275': 4,
 'P29353': 11,
 'P29371': 1,
 'P29375': 46,
 'P29400': 2,
 'P29475': 96,
 'P29508': 3,
 'P29536': 3,
 'P29622': 1,
 'P29728': 0,
 'P29966': 0,
 'P30043': 19,
 'P30049': 10,
 'P30260': 23,
 'P30281': 2,
 'P30307': 6,
 'P30533': 9,
 'P30542': 5,
 'P30838': 6,
 'P30968': 1,
 'P31040': 4,
 'P31269': 0,
 'P31271': 1,
 'P31276': 0,
 'P31391': 2,
 'P31645': 27,
 'P31785': 11,
 'P31941': 12,
 'P31948': 7,
 'P31949': 3,
 'P32239': 5,
 'P32241': 17,
 'P32246': 3,
 'P32298': 1,
 'P32320': 1,
 'P32321': 1,
 'P32322': 35,
 'P32754': 4,
 'P32881': 1,
 'P32942': 1,
 'P32970': 1,
 'P33763': 4,
 'P33778': 4,
 'P33981': 78,
 'P33991': 18,
 'P34897': 25,
 'P34910': 0,
 'P34949': 0,
 'P34982': 0,
 'P34995': 0,
 'P35221': 7,
 'P35232': 0,
 'P35237': 0,
 'P35241': 0,
 'P35243': 1,
 'P35270': 14,
 'P35321': 0,
 'P35326': 0,
 'P35414': 17,
 'P35452': 0,
 'P35462': 6,
 'P35555': 11,
 'P35556': 0,
 'P35573': 0,
 'P35637': 23,
 'P35670': 13,
 'P35712': 0,
 'P35858': 1,
 'P35914': 4,
 'P36021': 0,
 'P36222': 12,
 'P36382': 0,
 'P36406': 2,
 'P36776': 27,
 'P36871': 16,
 'P36897': 40,
 'P36941': 2,
 'P36959': 2,
 'P37023': 7,
 'P37059': 0,
 'P37198': 5,
 'P37235': 1,
 'P37802': 1,
 'P38571': 1,
 'P38935': 4,
 'P39019': 109,
 'P39023': 102,
 'P40121': 2,
 'P40145': 0,
 'P40222': 0,
 'P40259': 5,
 'P40425': 0,
 'P40429': 103,
 'P40616': 4,
 'P40925': 2,
 'P41091': 23,
 'P41145': 19,
 'P41146': 4,
 'P41159': 9,
 'P41181': 6,
 'P41225': 0,
 'P41240': 6,
 'P41252': 0,
 'P41440': 13,
 'P41968': 1,
 'P42126': 1,
 'P42224': 6,
 'P42331': 1,
 'P42566': 13,
 'P42658': 8,
 'P42680': 1,
 'P42685': 0,
 'P43005': 14,
 'P43007': 1,
 'P43268': 3,
 'P43358': 8,
 'P43487': 2,
 'P43489': 8,
 'P43629': 9,
 'P43681': 12,
 'P45452': 48,
 'P45973': 3,
 'P46020': 5,
 'P46059': 3,
 'P46060': 14,
 'P46089': 3,
 'P46094': 0,
 'P46098': 4,
 'P46100': 12,
 'P46109': 6,
 'P46597': 2,
 'P46695': 0,
 'P46783': 99,
 'P46934': 13,
 'P47211': 2,
 'P47710': 0,
 'P47712': 3,
 'P47736': 2,
 'P47756': 1,
 'P47870': 19,
 'P47871': 20,
 'P47900': 4,
 'P47914': 84,
 'P48039': 7,
 'P48066': 0,
 'P48304': 0,
 'P48506': 0,
 'P48509': 0,
 'P48547': 10,
 'P48728': 2,
 'P48730': 46,
 'P48735': 11,
 'P48742': 0,
 'P48775': 22,
 'P48960': 8,
 'P49019': 2,
 'P49137': 30,
 'P49189': 5,
 'P49238': 2,
 'P49247': 0,
 'P49279': 0,
 'P49326': 0,
 'P49356': 14,
 'P49450': 31,
 'P49458': 7,
 'P49593': 0,
 'P49619': 0,
 'P49639': 0,
 'P49641': 0,
 'P49643': 22,
 'P49703': 0,
 'P49715': 2,
 'P49748': 3,
 'P49761': 20,
 'P49767': 4,
 'P49771': 6,
 'P49790': 11,
 'P49821': 4,
 'P49842': 2,
 'P49863': 2,
 'P49895': 0,
 'P49901': 0,
 'P49908': 0,
 'P50151': 0,
 'P50213': 19,
 'P50226': 1,
 'P50406': 3,
 'P50416': 1,
 'P50458': 0,
 'P50461': 2,
 'P50479': 3,
 'P50552': 8,
 'P50553': 0,
 'P50748': 1,
 'P50895': 2,
 'P50897': 1,
 'P50993': 0,
 'P51114': 3,
 'P51168': 2,
 'P51512': 1,
 'P51530': 1,
 'P51531': 16,
 'P51532': 20,
 'P51617': 1,
 'P51648': 1,
 'P51795': 2,
 'P51797': 3,
 'P51813': 6,
 'P51817': 0,
 'P51857': 14,
 'P51884': 0,
 'P51946': 35,
 'P51956': 0,
 'P51959': 0,
 'P51970': 4,
 'P52597': 7,
 'P52732': 62,
 'P52739': 0,
 'P52789': 4,
 'P52798': 0,
 'P52799': 9,
 'P52849': 0,
 'P52926': 0,
 'P52952': 4,
 'P52961': 0,
 'P53365': 5,
 'P53567': 0,
 'P53618': 0,
 'P53674': 1,
 'P53701': 0,
 'P53804': 0,
 'P54098': 25,
 'P54105': 1,
 'P54198': 2,
 'P54289': 29,
 'P54296': 0,
 'P54315': 1,
 'P54707': 0,
 'P54710': 4,
 'P54802': 1,
 'P54821': 0,
 'P54840': 0,
 'P54845': 0,
 'P54855': 2,
 'P54920': 0,
 'P55000': 2,
 'P55036': 62,
 'P55072': 116,
 'P55082': 0,
 'P55157': 1,
 'P55196': 6,
 'P55259': 3,
 'P55263': 4,
 'P55273': 2,
 'P55287': 0,
 'P55327': 0,
 'P55809': 1,
 'P55854': 7,
 'P56270': 0,
 'P56381': 10,
 'P56470': 13,
 'P56559': 0,
 'P56589': 2,
 'P56645': 0,
 'P56851': 0,
 'P56880': 0,
 'P56962': 3,
 'P56975': 0,
 'P57075': 2,
 'P57088': 0,
 'P57105': 9,
 'P57678': 0,
 'P57730': 1,
 'P57735': 2,
 'P57737': 0,
 'P57771': 3,
 'P58397': 0,
 'P58418': 0,
 'P58876': 0,
 'P59044': 2,
 'P59666': 6,
 'P59827': 0,
 ...}

### Process PDB datas to get
: Chain Name, Chain Position, Valid Chain, Coverage, CovPer
 - Chain Name : ['A/B', 'C/D']
 - Chain Position : ['1-155', '184-317']
 - Valid Chain : ['1-155', '184-317'] (=Chain Position - Transig)
 - Coverage : 289 (=Total length of Valid Chain)
 - CovPer : 91.2 (=Coverage/Total_length*100)

In [ ]:
for key in models: #model[uniprot_id] = [{'Source','ID','Method','Resolution','Chains'}, {"}, ...]
    transig_pos_ = transig_pos[key] #'' or '1-xx'
    transig_end = int(transig_pos_.split('-')[1]) if transig_pos_ else 0 #transit_end = 0 or xx
    valid_length_ = valid_length[key]

    if models[key]: # models = [{},{},...] (else, models = [])
        for model in models[key]: # model = {'Source','ID','Method','Resolution','Chains'} of each key
            Chains = model['Chains'].split(', ') # Chains = ['~=x-x', '~=y-y']
            Chain_names = []
            Chain_pos = []
            Chain_valids = []
            total_coverage = 0

            for chain in Chains:
                Chain = chain.split('=') #Chain = ['~', 'x-x'] or ['-'](NO DATA)
                chain_valid=''
                coverage = 0

                if len(Chain) == 2:
                    chain_name, chain_pos = Chain #chain_pos = 'x-x'
                    try:
                        chain_start, chain_end = map(int, chain_pos.split('-'))
                        if chain_start > transig_end:
                            chain_valid = f'{chain_start}-{chain_end}'
                            coverage = chain_end - chain_start + 1
                        elif chain_end > transig_end:
                            chain_valid = f'{transig_end+1}-{chain_end}'
                            coverage = chain_end - transig_end
                    except: #chain_valid = ''
                        pass

                else: #Chain = ['-']
                    chain_name, chain_pos = 'NO DATA', 'NO DATA'

                total_coverage += coverage

                Chain_valids.append(chain_valid)
                Chain_names.append(chain_name)
                Chain_pos.append(chain_pos)

            CovPer = round(total_coverage / valid_length_ * 100, 1) if valid_length_ != 'error' else 0

            model['Chain Name'] = Chain_names
            model['Chain Position'] = Chain_pos
            model['Valid Chain'] = Chain_valids
            model['Coverage'] = total_coverage
            model['CovPer'] = CovPer

# models
# == [{'Source:''','ID:''','Method:''','Resolution:''','Chains:''','Chain Name:[]','Chain Position:[]','Valid Chain:[]','Coverage':--,'CovPer':--}, {}, {}, {}, ...]

In [ ]:
x = list(models.values())[:100]
y = list(models.keys())[:100]
for i in range(len(x)):
    print(y[i],":", x[i])

A0A0C5B5G6 : []
A0A1B0GTW7 : []
A0JNW5 : []
A0JP26 : []
A0PK11 : []
A1A4S6 : [{'Source': 'PDB', 'ID': '2MIO', 'Method': 'NMR', 'Resolution': '-', 'Chains': 'A=728-786', 'Chain Name': ['A'], 'Chain Position': ['728-786'], 'Valid Chain': ['728-786'], 'Coverage': 59, 'CovPer': 7.5}]
A1A519 : []
A1L190 : [{'Source': 'PDB', 'ID': '6H86', 'Method': 'X-ray', 'Resolution': '1.90 A', 'Chains': 'A/B=1-88', 'Chain Name': ['A/B'], 'Chain Position': ['1-88'], 'Valid Chain': ['1-88'], 'Coverage': 88, 'CovPer': 100.0}]
A1L3X0 : [{'Source': 'PDB', 'ID': '6Y7F', 'Method': 'X-ray', 'Resolution': '2.05 A', 'Chains': 'A/B=1-281', 'Chain Name': ['A/B'], 'Chain Position': ['1-281'], 'Valid Chain': ['1-281'], 'Coverage': 281, 'CovPer': 100.0}]
A1X283 : []
A2A2Y4 : []
A2RU14 : []
A2RUB6 : []
A2RUC4 : [{'Source': 'PDB', 'ID': '3AL5', 'Method': 'X-ray', 'Resolution': '2.50 A', 'Chains': 'A/B/C/D=1-315', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['1-315'], 'Valid Chain': ['1-315'], 'Coverage': 315, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '3AL6', 'Method': 'X-ray', 'Resolution': '2.80 A', 'Chains': 'A/B/C/D=1-315', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['1-315'], 'Valid Chain': ['1-315'], 'Coverage': 315, 'CovPer': 100.0}]
A4D1B5 : []
A4GXA9 : [{'Source': 'PDB', 'ID': '7F6L', 'Method': 'X-ray', 'Resolution': '3.20 A', 'Chains': 'B=1-379', 'Chain Name': ['B'], 'Chain Position': ['1-379'], 'Valid Chain': ['1-379'], 'Coverage': 379, 'CovPer': 100.0}]
A5D8V7 : [{'Source': 'PDB', 'ID': '8J07', 'Method': 'EM', 'Resolution': '4.10 A', 'Chains': 'm8/o8/q8/s8/u8=1-595', 'Chain Name': ['m8/o8/q8/s8/u8'], 'Chain Position': ['1-595'], 'Valid Chain': ['1-595'], 'Coverage': 595, 'CovPer': 100.0}]
A5PLL7 : []
A6BM72 : []
A6H8Y1 : [{'Source': 'PDB', 'ID': '5N9G', 'Method': 'X-ray', 'Resolution': '2.70 A', 'Chains': 'C/H=241-396', 'Chain Name': ['C/H'], 'Chain Position': ['241-396'], 'Valid Chain': ['241-396'], 'Coverage': 156, 'CovPer': 5.9}, {'Source': 'PDB', 'ID': '8ITY', 'Method': 'EM', 'Resolution': '3.90 A', 'Chains': 'W=1-2624', 'Chain Name': ['W'], 'Chain Position': ['1-2624'], 'Valid Chain': ['1-2624'], 'Coverage': 2624, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8IUE', 'Method': 'EM', 'Resolution': '4.10 A', 'Chains': 'W=1-2624', 'Chain Name': ['W'], 'Chain Position': ['1-2624'], 'Valid Chain': ['1-2624'], 'Coverage': 2624, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8IUH', 'Method': 'EM', 'Resolution': '3.40 A', 'Chains': 'W=1-2624', 'Chain Name': ['W'], 'Chain Position': ['1-2624'], 'Valid Chain': ['1-2624'], 'Coverage': 2624, 'CovPer': 100.0}]
A6NCS4 : []
A6NFY7 : []
A6NGG8 : [{'Source': 'PDB', 'ID': '7LXF', 'Method': 'X-ray', 'Resolution': '1.65 A', 'Chains': 'A=813-848', 'Chain Name': ['A'], 'Chain Position': ['813-848'], 'Valid Chain': ['813-848'], 'Coverage': 36, 'CovPer': 2.8}]
A6NI61 : []
A6NKB5 : []
A6NNB3 : []
A7E2V4 : []
A7MCY6 : []
A7MD48 : []
A7XYQ1 : []
A8MQ03 : []
A8MW99 : []
A9UHW6 : []
B1AK53 : []
B2RUY7 : []
B3KU38 : []
B6A8C7 : []
B7U540 : []
C9JLW8 : []
C9JRZ8 : []
D3W0D1 : [{'Source': 'PDB', 'ID': '4IOP', 'Method': 'X-ray', 'Resolution': '3.20 A', 'Chains': 'B=63-207', 'Chain Name': ['B'], 'Chain Position': ['63-207'], 'Valid Chain': ['63-207'], 'Coverage': 145, 'CovPer': 70.0}]
E0CX11 : []
O00115 : []
O00116 : []
O00159 : [{'Source': 'PDB', 'ID': '4BYF', 'Method': 'X-ray', 'Resolution': '2.74 A', 'Chains': 'A/C=36-760', 'Chain Name': ['A/C'], 'Chain Position': ['36-760'], 'Valid Chain': ['36-760'], 'Coverage': 725, 'CovPer': 68.2}]
O00161 : [{'Source': 'PDB', 'ID': '1NHL', 'Method': 'X-ray', 'Resolution': '2.30 A', 'Chains': 'A=23-76', 'Chain Name': ['A'], 'Chain Position': ['23-76'], 'Valid Chain': ['23-76'], 'Coverage': 54, 'CovPer': 25.6}, {'Source': 'PDB', 'ID': '3ZUS', 'Method': 'X-ray', 'Resolution': '2.95 A', 'Chains': 'A/B/C/D=150-211', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['150-211'], 'Valid Chain': ['150-211'], 'Coverage': 62, 'CovPer': 29.4}]
O00165 : []
O00168 : [{'Source': 'PDB', 'ID': '2JO1', 'Method': 'NMR', 'Resolution': '-', 'Chains': 'A=21-92', 'Chain Name': ['A'], 'Chain Position': ['21-92'], 'Valid Chain': ['21-92'], 'Coverage': 72, 'CovPer': 100.0}]
O00214 : [{'Source': 'PDB', 'ID': '2YRO', 'Method': 'NMR', 'Resolution': '-', 'Chains': 'A=176-317', 'Chain Name': ['A'], 'Chain Position': ['176-317'], 'Valid Chain': ['176-317'], 'Coverage': 142, 'CovPer': 44.8}, {'Source': 'PDB', 'ID': '2YV8', 'Method': 'X-ray', 'Resolution': '1.92 A', 'Chains': 'A=1-152', 'Chain Name': ['A'], 'Chain Position': ['1-152'], 'Valid Chain': ['1-152'], 'Coverage': 152, 'CovPer': 47.9}, {'Source': 'PDB', 'ID': '2YXS', 'Method': 'X-ray', 'Resolution': '2.13 A', 'Chains': 'A=1-152', 'Chain Name': ['A'], 'Chain Position': ['1-152'], 'Valid Chain': ['1-152'], 'Coverage': 152, 'CovPer': 47.9}, {'Source': 'PDB', 'ID': '3AP4', 'Method': 'X-ray', 'Resolution': '2.33 A', 'Chains': 'A/B/C/D=1-154', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3AP5', 'Method': 'X-ray', 'Resolution': '1.92 A', 'Chains': 'A=1-154', 'Chain Name': ['A'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3AP6', 'Method': 'X-ray', 'Resolution': '1.58 A', 'Chains': 'A/B/C/D=1-154', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3AP7', 'Method': 'X-ray', 'Resolution': '1.53 A', 'Chains': 'A=1-154', 'Chain Name': ['A'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3AP9', 'Method': 'X-ray', 'Resolution': '1.33 A', 'Chains': 'A=1-154', 'Chain Name': ['A'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3APB', 'Method': 'X-ray', 'Resolution': '1.95 A', 'Chains': 'A/B=1-154', 'Chain Name': ['A/B'], 'Chain Position': ['1-154'], 'Valid Chain': ['1-154'], 'Coverage': 154, 'CovPer': 48.6}, {'Source': 'PDB', 'ID': '3OJB', 'Method': 'X-ray', 'Resolution': '3.01 A', 'Chains': 'A/B/C/D=186-315', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['186-315'], 'Valid Chain': ['186-315'], 'Coverage': 130, 'CovPer': 41.0}, {'Source': 'PDB', 'ID': '3VKL', 'Method': 'X-ray', 'Resolution': '2.55 A', 'Chains': 'A/B=1-155, A/B=184-317', 'Chain Name': ['A/B', 'A/B'], 'Chain Position': ['1-155', '184-317'], 'Valid Chain': ['1-155', '184-317'], 'Coverage': 289, 'CovPer': 91.2}, {'Source': 'PDB', 'ID': '3VKM', 'Method': 'X-ray', 'Resolution': '2.98 A', 'Chains': 'A/B=1-155, A/B=184-317', 'Chain Name': ['A/B', 'A/B'], 'Chain Position': ['1-155', '184-317'], 'Valid Chain': ['1-155', '184-317'], 'Coverage': 289, 'CovPer': 91.2}, {'Source': 'PDB', 'ID': '3VKN', 'Method': 'X-ray', 'Resolution': '1.98 A', 'Chains': 'A/B=1-153', 'Chain Name': ['A/B'], 'Chain Position': ['1-153'], 'Valid Chain': ['1-153'], 'Coverage': 153, 'CovPer': 48.3}, {'Source': 'PDB', 'ID': '3VKO', 'Method': 'X-ray', 'Resolution': '2.08 A', 'Chains': 'A/B=1-153', 'Chain Name': ['A/B'], 'Chain Position': ['1-153'], 'Valid Chain': ['1-153'], 'Coverage': 153, 'CovPer': 48.3}, {'Source': 'PDB', 'ID': '4BMB', 'Method': 'X-ray', 'Resolution': '1.35 A', 'Chains': 'A=4-153', 'Chain Name': ['A'], 'Chain Position': ['4-153'], 'Valid Chain': ['4-153'], 'Coverage': 150, 'CovPer': 47.3}, {'Source': 'PDB', 'ID': '4BME', 'Method': 'X-ray', 'Resolution': '2.00 A', 'Chains': 'A/B=4-155', 'Chain Name': ['A/B'], 'Chain Position': ['4-155'], 'Valid Chain': ['4-155'], 'Coverage': 152, 'CovPer': 47.9}, {'Source': 'PDB', 'ID': '4FQZ', 'Method': 'X-ray', 'Resolution': '2.80 A', 'Chains': 'A=1-155, A=184-317', 'Chain Name': ['A', 'A'], 'Chain Position': ['1-155', '184-317'], 'Valid Chain': ['1-155', '184-317'], 'Coverage': 289, 'CovPer': 91.2}, {'Source': 'PDB', 'ID': '4GXL', 'Method': 'X-ray', 'Resolution': '2.02 A', 'Chains': 'A=186-317', 'Chain Name': ['A'], 'Chain Position': ['186-317'], 'Valid Chain': ['186-317'], 'Coverage': 132, 'CovPer': 41.6}, {'Source': 'PDB', 'ID': '4HAN', 'Method': 'X-ray', 'Resolution': '2.55 A', 'Chains': 'A/B=1-155, A/B=184-317', 'Chain Name': ['A/B', 'A/B'], 'Chain Position': ['1-155', '184-317'], 'Valid Chain': ['1-155', '184-317'], 'Coverage': 289, 'CovPer': 91.2}, {'Source': 'PDB', 'ID': '5GZC', 'Method': 'X-ray', 'Resolution': '1.08 A', 'Chains': 'A=7-158', 'Chain Name': ['A'], 'Chain Position': ['7-158'], 'Valid Chain': ['7-158'], 'Coverage': 152, 'CovPer': 47.9}, {'Source': 'PDB', 'ID': '5GZD', 'Method': 'X-ray', 'Resolution': '1.19 A', 'Chains': 'A=7-154', 'Chain Name': ['A'], 'Chain Position': ['7-154'], 'Valid Chain': ['7-154'], 'Coverage': 148, 'CovPer': 46.7}, {'Source': 'PDB', 'ID': '5GZE', 'Method': 'X-ray', 'Resolution': '1.32 A', 'Chains': 'A=7-154', 'Chain Name': ['A'], 'Chain Position': ['7-154'], 'Valid Chain': ['7-154'], 'Coverage': 148, 'CovPer': 46.7}, {'Source': 'PDB', 'ID': '5GZF', 'Method': 'X-ray', 'Resolution': '2.00 A', 'Chains': 'A=1-186', 'Chain Name': ['A'], 'Chain Position': ['1-186'], 'Valid Chain': ['1-186'], 'Coverage': 186, 'CovPer': 58.7}, {'Source': 'PDB', 'ID': '5GZG', 'Method': 'X-ray', 'Resolution': '2.00 A', 'Chains': 'A=1-186', 'Chain Name': ['A'], 'Chain Position': ['1-186'], 'Valid Chain': ['1-186'], 'Coverage': 186, 'CovPer': 58.7}, {'Source': 'PDB', 'ID': '5T7I', 'Method': 'X-ray', 'Resolution': '2.00 A', 'Chains': 'A=1-155', 'Chain Name': ['A'], 'Chain Position': ['1-155'], 'Valid Chain': ['1-155'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '5T7S', 'Method': 'X-ray', 'Resolution': '1.90 A', 'Chains': 'A=1-155', 'Chain Name': ['A'], 'Chain Position': ['1-155'], 'Valid Chain': ['1-155'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '5T7T', 'Method': 'X-ray', 'Resolution': '1.96 A', 'Chains': 'A=1-155', 'Chain Name': ['A'], 'Chain Position': ['1-155'], 'Valid Chain': ['1-155'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '5T7U', 'Method': 'X-ray', 'Resolution': '1.58 A', 'Chains': 'A=1-155', 'Chain Name': ['A'], 'Chain Position': ['1-155'], 'Valid Chain': ['1-155'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '5VWG', 'Method': 'X-ray', 'Resolution': '2.10 A', 'Chains': 'A=1-155', 'Chain Name': ['A'], 'Chain Position': ['1-155'], 'Valid Chain': ['1-155'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '6W4Z', 'Method': 'X-ray', 'Resolution': '1.59 A', 'Chains': 'A/B=2-154', 'Chain Name': ['A/B'], 'Chain Position': ['2-154'], 'Valid Chain': ['2-154'], 'Coverage': 153, 'CovPer': 48.3}, {'Source': 'PDB', 'ID': '6Z6Y', 'Method': 'X-ray', 'Resolution': '1.34 A', 'Chains': 'A=1-163', 'Chain Name': ['A'], 'Chain Position': ['1-163'], 'Valid Chain': ['1-163'], 'Coverage': 163, 'CovPer': 51.4}, {'Source': 'PDB', 'ID': '7AEN', 'Method': 'X-ray', 'Resolution': '1.60 A', 'Chains': 'A/B=7-156', 'Chain Name': ['A/B'], 'Chain Position': ['7-156'], 'Valid Chain': ['7-156'], 'Coverage': 150, 'CovPer': 47.3}, {'Source': 'PDB', 'ID': '7ALS', 'Method': 'X-ray', 'Resolution': '1.35 A', 'Chains': 'A/B=4-158', 'Chain Name': ['A/B'], 'Chain Position': ['4-158'], 'Valid Chain': ['4-158'], 'Coverage': 155, 'CovPer': 48.9}, {'Source': 'PDB', 'ID': '7P1M', 'Method': 'X-ray', 'Resolution': '1.52 A', 'Chains': 'A/B=6-156', 'Chain Name': ['A/B'], 'Chain Position': ['6-156'], 'Valid Chain': ['6-156'], 'Coverage': 151, 'CovPer': 47.6}, {'Source': 'PDB', 'ID': '8CM8', 'Method': 'X-ray', 'Resolution': '1.22 A', 'Chains': 'A/B=1-317', 'Chain Name': ['A/B'], 'Chain Position': ['1-317'], 'Valid Chain': ['1-317'], 'Coverage': 317, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8HL9', 'Method': 'X-ray', 'Resolution': '1.60 A', 'Chains': 'A=171-317', 'Chain Name': ['A'], 'Chain Position': ['171-317'], 'Valid Chain': ['171-317'], 'Coverage': 147, 'CovPer': 46.4}]
O00237 : []
O00254 : []
O00268 : [{'Source': 'PDB', 'ID': '1H3O', 'Method': 'X-ray', 'Resolution': '2.30 A', 'Chains': 'A/C=872-945', 'Chain Name': ['A/C'], 'Chain Position': ['872-945'], 'Valid Chain': ['872-945'], 'Coverage': 74, 'CovPer': 6.8}, {'Source': 'PDB', 'ID': '2P6V', 'Method': 'X-ray', 'Resolution': '2.00 A', 'Chains': 'A=575-688', 'Chain Name': ['A'], 'Chain Position': ['575-688'], 'Valid Chain': ['575-688'], 'Coverage': 114, 'CovPer': 10.5}, {'Source': 'PDB', 'ID': '6MZC', 'Method': 'EM', 'Resolution': '4.50 A', 'Chains': 'E=1-1085', 'Chain Name': ['E'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '6MZD', 'Method': 'EM', 'Resolution': '9.80 A', 'Chains': 'D=1-1085', 'Chain Name': ['D'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '6MZL', 'Method': 'EM', 'Resolution': '23.00 A', 'Chains': 'D/E=1-1085', 'Chain Name': ['D/E'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '6MZM', 'Method': 'EM', 'Resolution': '7.50 A', 'Chains': 'D=61-1085', 'Chain Name': ['D'], 'Chain Position': ['61-1085'], 'Valid Chain': ['61-1085'], 'Coverage': 1025, 'CovPer': 94.5}, {'Source': 'PDB', 'ID': '7EDX', 'Method': 'EM', 'Resolution': '4.50 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EG7', 'Method': 'EM', 'Resolution': '6.20 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EG8', 'Method': 'EM', 'Resolution': '7.40 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EG9', 'Method': 'EM', 'Resolution': '3.70 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGA', 'Method': 'EM', 'Resolution': '4.10 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGB', 'Method': 'EM', 'Resolution': '3.30 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGC', 'Method': 'EM', 'Resolution': '3.90 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGD', 'Method': 'EM', 'Resolution': '6.75 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGE', 'Method': 'EM', 'Resolution': '9.00 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGF', 'Method': 'EM', 'Resolution': '3.16 A', 'Chains': 'd=1-1085', 'Chain Name': ['d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGG', 'Method': 'EM', 'Resolution': '2.77 A', 'Chains': 'D=1-1085', 'Chain Name': ['D'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGI', 'Method': 'EM', 'Resolution': '9.82 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7EGJ', 'Method': 'EM', 'Resolution': '8.64 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7ENA', 'Method': 'EM', 'Resolution': '4.07 A', 'Chains': 'DD/Dd=1-1085', 'Chain Name': ['DD/Dd'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '7ENC', 'Method': 'EM', 'Resolution': '4.13 A', 'Chains': 'DD/Dd=1-1085', 'Chain Name': ['DD/Dd'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8GXQ', 'Method': 'EM', 'Resolution': '5.04 A', 'Chains': 'DD/Dd=1-1085', 'Chain Name': ['DD/Dd'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8GXS', 'Method': 'EM', 'Resolution': '4.16 A', 'Chains': 'DD/Dd=1-1085', 'Chain Name': ['DD/Dd'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAK', 'Method': 'EM', 'Resolution': '5.47 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAL', 'Method': 'EM', 'Resolution': '8.52 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAN', 'Method': 'EM', 'Resolution': '6.07 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAO', 'Method': 'EM', 'Resolution': '6.40 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAP', 'Method': 'EM', 'Resolution': '5.85 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAQ', 'Method': 'EM', 'Resolution': '6.29 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAR', 'Method': 'EM', 'Resolution': '7.20 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}, {'Source': 'PDB', 'ID': '8WAS', 'Method': 'EM', 'Resolution': '6.13 A', 'Chains': 'D/d=1-1085', 'Chain Name': ['D/d'], 'Chain Position': ['1-1085'], 'Valid Chain': ['1-1085'], 'Coverage': 1085, 'CovPer': 100.0}]
O00291 : [{'Source': 'PDB', 'ID': '2NO2', 'Method': 'X-ray', 'Resolution': '2.80 A', 'Chains': 'A=482-586', 'Chain Name': ['A'], 'Chain Position': ['482-586'], 'Valid Chain': ['482-586'], 'Coverage': 105, 'CovPer': 10.1}, {'Source': 'PDB', 'ID': '2QA7', 'Method': 'X-ray', 'Resolution': '2.80 A', 'Chains': 'A/B/C/D=370-481', 'Chain Name': ['A/B/C/D'], 'Chain Position': ['370-481'], 'Valid Chain': ['370-481'], 'Coverage': 112, 'CovPer': 10.8}, {'Source': 'PDB', 'ID': '3I00', 'Method': 'X-ray', 'Resolution': '2.30 A', 'Chains': 'A/B=361-480', 'Chain Name': ['A/B'], 'Chain Position': ['361-480'], 'Valid Chain': ['361-480'], 'Coverage': 120, 'CovPer': 11.6}]
O00300 : [{'Source': 'PDB', 'ID': '3URF', 'Method': 'X-ray', 'Resolution': '2.70 A', 'Chains': 'Z=22-186', 'Chain Name': ['Z'], 'Chain Position': ['22-186'], 'Valid Chain': ['22-186'], 'Coverage': 165, 'CovPer': 43.4}]
O00322 : []

### Filter models (with Resolution, CovPer)

In [ ]:
resol_cut, covper_cut = 2.50, 80 #set cutoff values

In [ ]:
filtered_models = {}
filtered_counts = {}

for key in models:
  valid_length_ = valid_length[key]
  filtered_model= []
  filtered_count = 0
  if models[key]:
    for model in models[key]:
      resol = float(model['Resolution'].split(' ')[0]) if model['Resolution'] != '-' else 10
      covper = model['CovPer']
      if resol <= resol_cut and covper >= covper_cut:
        filtered_model.append(model['ID'])
        filtered_count += 1
  filtered_models[key] = filtered_model
  filtered_counts[key] = filtered_count

In [ ]:
list(filtered_models.values())[:100]
list(filtered_counts.values())[:100]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 7,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 37,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

## Result : Datas into DataFrame

In [40]:
df = pd.DataFrame({'Protein name' : protein_names,
                   'Type' : transig_type,
                   'Position' : transig_pos,
                   'Total Length' : total_length,
                   'Valid length' : valid_length,
                   'Valid position' : valid_pos,
                   'PDB count' : model_count,
                   'PDB models' : models,
                   'Filtered count' : filtered_counts,
                   'Filtered ID (2.50A & 80%)' : filtered_models})

In [41]:
df.head(20)

,Protein name,Type,Position,Total Length,Valid length,Valid position,PDB count,PDB models,Filtered count,Filtered ID (2.50A & 80%)
A0A0C5B5G6,Mitochondrial-derived peptide MOTS-c (Mitochon...,,,16,16,1-16,0,[],0,[]
A0A1B0GTW7,Ciliated left-right organizer metallopeptidase...,SIGNAL,1-20,788,768,21-788,0,[],0,[]
A0JNW5,Bridge-like lipid transfer protein family memb...,,,1464,1464,1-1464,0,[],0,[]
A0JP26,POTE ankyrin domain family member B3,,,581,581,1-581,0,[],0,[]
A0PK11,Clarin-2,,,232,232,1-232,0,[],0,[]
A1A4S6,Rho GTPase-activating protein 10 (GTPase regul...,,,786,786,1-786,1,"[{'Source': 'PDB', 'ID': '2MIO', 'Method': 'NM...",0,[]
A1A519,Protein FAM170A (Zinc finger domain-containing...,,,330,330,1-330,0,[],0,[]
A1L190,Synaptonemal complex central element protein 3...,,,88,88,1-88,1,"[{'Source': 'PDB', 'ID': '6H86', 'Method': 'X-...",1,[6H86]
A1L3X0,Very long chain fatty acid elongase 7 (EC 2.3....,,,281,281,1-281,1,"[{'Source': 'PDB', 'ID': '6Y7F', 'Method': 'X-...",1,[6Y7F]
A1X283,SH3 and PX domain-containing protein 2B (Adapt...,,,911,911,1-911,0,[],0,[]
A2A2Y4,FERM domain-containing protein 3 (Band 4.1-lik...,,,597,597,1-597,0,[],0,[]
A2RU14,Transmembrane protein 218,,,115,115,1-115,0,[],0,[]
A2RUB6,Coiled-coil domain-containing protein 66,,,948,948,1-948,0,[],0,[]
A2RUC4,tRNA wybutosine-synthesizing protein 5 (hTYW5)...,,,315,315,1-315,2,"[{'Source': 'PDB', 'ID': '3AL5', 'Method': 'X-...",1,[3AL5]
A4D1B5,Gamma-secretase-activating protein (GSAP) (Pro...,,,854,854,1-854,0,[],0,[]
A4GXA9,Probable crossover junction endonuclease EME2 ...,,,379,379,1-379,1,"[{'Source': 'PDB', 'ID': '7F6L', 'Method': 'X-...",0,[]
A5D8V7,Outer dynein arm-docking complex subunit 3 (Co...,,,595,595,1-595,1,"[{'Source': 'PDB', 'ID': '8J07', 'Method': 'EM...",0,[]
A5PLL7,Plasmanylethanolamine desaturase 1 (EC 1.14.19...,,,270,270,1-270,0,[],0,[]
A6BM72,Multiple epidermal growth factor-like domains ...,SIGNAL,1-19,1044,1025,20-1044,0,[],0,[]
A6H8Y1,Transcription factor TFIIIB component B'' homo...,,,2624,2624,1-2624,4,"[{'Source': 'PDB', 'ID': '5N9G', 'Method': 'X-...",0,[]

## Only 2,260 IDs have filtered model (resol < 2.50 A & CovPer > 80%)
 - Total : 20,417 IDs
 - count_count : distribution of model_count {0: 11906, 1: 2063, 2: 1213, ...}
 => 11,906 IDs have 0 PDB model
 => 8,511 IDs have PDB model

 - filtered_count_count : distribution of filtered_count {0: 18157, 1: 810, 2: 385, 3: 203, 4: 134,...} => 18,157 IDs have 0 filtered_PDB model

In [ ]:
count_count = {} #distribution of model_count {0: 11906, 1: 2063, 2: 1213, ...} => 11906 IDs have 0 PDB model
sorted_count = {} #sorted by size (==count_count)

for num in model_count.values():
    if num in count_count:
        count_count[num] += 1
    else:
        count_count[num] = 1

for k in sorted(count_count):
    sorted_count[k]=count_count[k]

sorted_count #{0: 11906, 1: 2063, 2: 1213, ..., 1116: 1, 1196: 1}

{0: 11906,
 1: 2063,
 2: 1213,
 3: 830,
 4: 709,
 5: 455,
 6: 362,
 7: 286,
 8: 223,
 9: 228,
 10: 174,
 11: 179,
 12: 112,
 13: 119,
 14: 109,
 15: 81,
 16: 67,
 17: 56,
 18: 55,
 19: 63,
 20: 49,
 21: 45,
 22: 49,
 23: 46,
 24: 37,
 25: 42,
 26: 39,
 27: 28,
 28: 18,
 29: 28,
 30: 14,
 31: 20,
 32: 23,
 33: 22,
 34: 14,
 35: 14,
 36: 17,
 37: 15,
 38: 11,
 39: 14,
 40: 17,
 41: 13,
 42: 11,
 43: 9,
 44: 11,
 45: 9,
 46: 9,
 47: 9,
 48: 11,
 49: 39,
 50: 9,
 51: 8,
 52: 16,
 53: 6,
 54: 9,
 55: 9,
 56: 5,
 57: 3,
 58: 8,
 59: 4,
 60: 6,
 61: 8,
 62: 7,
 63: 3,
 64: 12,
 65: 8,
 66: 7,
 67: 17,
 68: 23,
 69: 9,
 70: 5,
 71: 1,
 72: 1,
 73: 5,
 74: 5,
 75: 2,
 76: 1,
 77: 3,
 78: 4,
 79: 3,
 81: 1,
 82: 2,
 83: 3,
 84: 5,
 85: 1,
 86: 2,
 87: 3,
 88: 5,
 89: 3,
 90: 3,
 91: 4,
 92: 3,
 93: 5,
 94: 6,
 95: 8,
 96: 2,
 97: 5,
 98: 2,
 99: 4,
 100: 4,
 101: 6,
 102: 6,
 103: 11,
 104: 3,
 105: 5,
 106: 6,
 107: 3,
 108: 7,
 109: 4,
 110: 3,
 111: 5,
 112: 3,
 113: 4,
 114: 6,
 115: 1,
 116: 3,
 117: 2,
 118: 4,
 120: 2,
 121: 1,
 126: 1,
 128: 1,
 129: 1,
 130: 1,
 133: 2,
 136: 1,
 140: 1,
 142: 1,
 143: 2,
 144: 2,
 146: 1,
 151: 1,
 152: 1,
 154: 1,
 155: 1,
 156: 2,
 158: 1,
 160: 2,
 161: 1,
 162: 2,
 164: 1,
 168: 1,
 172: 1,
 176: 1,
 182: 1,
 186: 1,
 211: 1,
 214: 1,
 220: 1,
 221: 1,
 231: 1,
 234: 1,
 235: 1,
 241: 1,
 243: 1,
 245: 1,
 246: 1,
 257: 1,
 258: 1,
 264: 1,
 280: 1,
 283: 1,
 285: 1,
 289: 1,
 294: 1,
 297: 1,
 314: 1,
 315: 1,
 316: 1,
 317: 1,
 318: 1,
 321: 1,
 322: 1,
 340: 1,
 347: 1,
 355: 1,
 356: 1,
 361: 1,
 379: 1,
 385: 1,
 396: 1,
 412: 1,
 413: 1,
 431: 1,
 433: 1,
 449: 1,
 454: 1,
 456: 1,
 462: 1,
 469: 1,
 584: 1,
 757: 1,
 789: 1,
 1116: 1,
 1196: 1}

In [ ]:
filtered_count_count = {} #distribution of filtered_count {0: 18157, 1: 810, 2: 385, 3: 203, 4: 134,...} => 18157 IDs have 0 filtered_PDB model
filtered_sorted_count = {} #sorted by size (==filtered_count_count)

for num in filtered_counts.values():
    if num in filtered_count_count:
        filtered_count_count[num] += 1
    else:
        filtered_count_count[num] = 1

for k in sorted(filtered_count_count):
    filtered_sorted_count[k]=filtered_count_count[k]

filtered_sorted_count #{0: 18157, 1: 810, 2: 385, ... ,876: 1, 1104: 1} in 2.5 A & 80%

{0: 18157,
 1: 810,
 2: 385,
 3: 203,
 4: 134,
 5: 123,
 6: 64,
 7: 59,
 8: 36,
 9: 37,
 10: 23,
 11: 21,
 12: 52,
 13: 17,
 14: 29,
 15: 20,
 16: 17,
 17: 35,
 18: 11,
 19: 9,
 20: 10,
 21: 9,
 22: 5,
 23: 6,
 24: 6,
 25: 3,
 26: 3,
 27: 3,
 28: 6,
 29: 3,
 30: 4,
 31: 3,
 32: 4,
 33: 3,
 34: 8,
 35: 3,
 36: 2,
 37: 4,
 38: 2,
 39: 4,
 40: 4,
 41: 1,
 42: 1,
 44: 2,
 45: 1,
 46: 1,
 47: 1,
 48: 6,
 49: 5,
 50: 1,
 52: 1,
 53: 3,
 55: 1,
 57: 2,
 60: 1,
 61: 1,
 62: 1,
 63: 2,
 64: 1,
 66: 2,
 68: 1,
 69: 2,
 70: 1,
 71: 1,
 73: 3,
 77: 2,
 80: 2,
 82: 1,
 84: 1,
 87: 1,
 88: 1,
 90: 2,
 92: 1,
 97: 1,
 102: 1,
 105: 1,
 106: 1,
 134: 1,
 137: 1,
 138: 1,
 151: 1,
 152: 1,
 174: 1,
 194: 1,
 205: 1,
 210: 1,
 217: 1,
 218: 1,
 240: 1,
 260: 1,
 262: 1,
 265: 1,
 275: 1,
 287: 1,
 380: 1,
 381: 1,
 394: 1,
 432: 1,
 876: 1,
 1104: 1}

In [83]:
https://rest.uniprot.org/uniprotkb/search?query=accession:Q9HBH1&fields=xref_alphafolddb&format=tsv

SyntaxError: invalid syntax (<ipython-input-83-bfefca94410e>, line 1)